// GENERATED by scripts/generate.mjs from kit 2.1.1. Do not edit.
import tokenData from './tokens.json';
type DeepReadonly<T> = { readonly [K in keyof T]: T[K] extends object ? DeepReadonly<T[K]> : T[K] };
export const tokens: DeepReadonly<typeof tokenData> = tokenData;
export const colors = tokens.colors;
