import fs from 'node:fs';
import path from 'node:path';
const dir=import.meta.dirname;
const source=JSON.parse(fs.readFileSync(path.join(dir,'source-review.json'),'utf8'));
const summary=JSON.parse(fs.readFileSync(path.join(dir,'review-summary.json'),'utf8'));
const live=JSON.parse(fs.readFileSync(path.join(dir,'live-route-review.json'),'utf8')).observations;
// This catalog owns this audit only. The canonical UI implementation plan remains unchanged.
const findings=[
 ['UX01','P1','Lỗi đã tái hiện','Liên kết checklist dẫn nhầm tác vụ','R33,R24,R25','workspace/index.tsx:137','Nút Duyệt góp ý mở /knowledge/feedback. Router bắt feedback làm knowledgeId ở R24; màn hiện không tìm thấy dữ liệu. R25 đúng là /knowledge/review.','Đường dẫn nghiệp vụ viết trực tiếp; kiểm một URL có match router không phát hiện được đích sai do route động.','Sửa đích theo R25; dùng builder nhỏ theo route đã sở hữu; kiểm cả nhãn và màn đích của các CTA xuyên module.','Bấm CTA từ thiết lập phải mở Duyệt phản hồi AI. Giữ /knowledge/:knowledgeId hoạt động, không tạo alias giả cho feedback.'],
 ['UX02','P1','Sai nghĩa nghiệp vụ đã xác nhận','Trạng thái dùng cùng từ nhưng khác nghĩa','R15,R16,R50','inventory/index.tsx:128; shared/model/labels.ts:3','QU-003 còn3, ngưỡng5 và TU-008 còn2, ngưỡng3 đều bị gắn Bị chặn. Lịch sử nhập kho hiện Phiếu thu cho receipt. Kỳ kế toán open hiện Đang xử lý.','Suy trạng thái ngăn xử lý từ ngưỡng tồn; từ điển global không nhận domain nên receipt/open bị dùng chung nghĩa.','Tách trình bày theo domain; cảnh báo tồn có các nhãn Còn hàng/Sắp hết/Hết hàng dựa trên snapshot. Biến động kho receipt phải là Nhập kho, kỳ open là Đang mở. Không sửa quy tắc bán hàng hoặc số liệu tại client.','Kiểm biên0, bằng ngưỡng, dưới/trên ngưỡng; cùng receipt ở tài chính vẫn là Phiếu thu. Kỳ open/locked trình bày đúng domain.'],
 ['UX03','P1','Thiếu ngữ cảnh đã xác nhận','Dialog rủi ro chưa chỉ rõ đối tượng','R11,R12,R19,R24,R29,R30,R32,R40,R51,R52','shared/ui/components.tsx:454','Mở thu hồi user-warehouse, ngừng danh mục Quần và xóa kết nối AI: dialog không ghi đối tượng đã chọn; CTA đều là Xác nhận. Đã kiểm source23 consumer, không mở đủ23.','Shared ConfirmDialog chỉ nhận title/description, không có nhãn hành động riêng; consumer viết mô tả chung và bỏ identity.','Thêm confirmLabel tương thích mặc định; consumer truyền tên/mã được phép hiển thị, tác động và đối tượng. Giữ reason/version/permission/busy/draft guard.','Mỗi thao tác rủi ro đọc độc lập vẫn biết tác động lên ai/cái gì; nhãn Thu hồi quyền/Ngừng dùng/Xóa kết nối. Escape/Hủy/Đóng không thực thi lệnh. Không focus mặc định vào hành động nguy hiểm.'],
 ['UX04','P1','Mất nháp đã tái hiện','Tạo cửa hàng chưa được bảo vệ khi rời','R03','workspace/index.tsx:56','Nhập Nháp kiểm tra UX, bấm Quay lại: không có cảnh báo. Browser Back quay lại thì Tên cửa hàng rỗng. Không tạo shop trong audit.','Onboarding nằm ngoài Shell có blocker; chỉ dùng useState và không đăng ký draft guard.','Bảo vệ form ở owner thích hợp cho route global; so sánh name/currency/timezone, chỉ sạch sau commit hoặc người dùng chọn bỏ. Không thêm localStorage chứa dữ liệu nhạy cảm.','Kiểm Quay lại, link, Back và reload; form sạch không cảnh báo, commit thành công không cảnh báo sai.'],
 ['UX05','P1','Mất ngữ cảnh đã tái hiện','Nút về danh sách làm mất bộ lọc','R09,R11; rà R07,R08,R17,R19,R23,R24','catalog/index.tsx:142','Tìm AO-002 tạo URL ?q=AO-002, mở Chi tiết rồi bấm Danh sách: trở về /products và8 sản phẩm, bộ lọc mất. Browser Back và nút Danh sách là hai hành vi khác nhau.','Link quay lại chỉ biết path gốc; thiếu return context của danh sách. URL filter đang đúng nhưng không được mang qua liên kết detail.','Giữ đường về chứa q/cursor/filter của đúng shop/route; kiểm allowlist nội bộ. Truy cập chi tiết trực tiếp có fallback về danh sách gốc.','Search/filter/cursor rồi mở chi tiết và quay lại qua UI giữ đúng ngữ cảnh; đổi shop không hồi phục bộ lọc scope cũ. Không dựa vào history -1 mù quáng.'],
 ['UX06','P2','Nhãn thô đã xác nhận','Tiếng Việt và thuật ngữ chưa đồng nhất','R02,R06,R08,R23,R29,R30,R34,R38,R39,R43,R48,R50,R51,R54','customers/index.tsx:134; shared/model/labels.ts:1','Hồ sơ khách hiện completed/draft; tin nhắn read/delivered; AI supported/structuredOutput; phê duyệt consumed; đổi trả inspected; case question; channel in_app.','Một số consumer bỏ qua mapper; mapper thiếu enum và fallback nguyên key. Mã kỹ thuật và nhãn nghiệp vụ chưa có vai trò trình bày riêng.','Dùng nhãn domain tiếng Việt cho status/kind/capability; technical code giữ ở dòng phụ hoặc chi tiết khi có giá trị chẩn đoán. Không đổi mã API hoặc SKU.','Enum canonical trên các trạng thái khả dụng có nhãn đầy đủ; unknown thật hiện Chưa xác định, không dùng xanh thành công. Kiểm cả accessible name.'],
 ['UX07','P2','Metadata và trạng thái tìm kiếm đã xác nhận','Định hướng route/tab chưa đủ rõ','Tất cả54 route; Shell','app/router.tsx; app/Shell.tsx:110; apps/web/index.html','54 route cùng title BotSales AI — Graphite Gold. Tìm màn hình zzzzzz làm menu trống nhưng không có giải thích không tìm thấy hoặc nút xóa. Breadcrumb màn tạo sản phẩm/đơn vẫn dùng ngữ cảnh chi tiết.','Title chỉ khai báo HTML; breadcrumb dựa title tổng quát; search sidebar chỉ lọc danh sách.','Title theo tác vụ từ route manifest; không đưa PII vào title. Sidebar có trạng thái không tìm thấy và Xóa tìm kiếm; breadcrumb phân biệt tạo/sửa/chi tiết.','Title đổi khi điều hướng, kể cả forbidden/not-found. Xóa search khôi phục menu và focus input. Tên route không lấy dữ liệu thuộc scope cũ.'],
 ['UX08','P2','Cải tiến phân cấp từ UI/source','Nội dung giải thích lấn tác vụ chính','R01,R03,R04,R06,R18,R23,R26,R31,R33,R34,R38,R40,R42,R51,R52,R53','operations/index.tsx; fulfillment/index.tsx; bot/index.tsx','R38 panel ủy quyền mẫu trước hàng phê duyệt; R42 panel phí/vùng mẫu trước vận đơn. Viewport1280x720: bảng R38 bắt đầu y637, R42 y775. Nhiều đoạn hiển thị tên API/schema, quy tắc AI lập trình cho người vận hành.','Sắp xếp theo tính năng/evidence được thêm, chưa ưu tiên tần suất và quyết định vận hành; copy của hồ sơ kỹ thuật đi vào UI.','Đưa queue/list thật trong phạm vi mock lên trước; preview ở disclosure/tab rõ nhãn. Giữ banner mô phỏng và điều kiện an toàn có ảnh hưởng quyết định. Viết trợ giúp theo tác vụ bằng tiếng Việt; chi tiết kỹ thuật mở khi cần.','Mở trang thấy việc chính và CTA liên quan trước phần thử; không đánh đồng preview với thao tác thật. Đo task position ở viewport thực, không chỉ padding.'],
 ['UX09','P2','Trình bày dữ liệu đã xác nhận','Identity và ngày còn khó đọc','R16,R17,R19,R24,R26,R32,R34,R41,R46,R47,R48,R50,R51','orders/index.tsx; finance/index.tsx:229,322','Đơn hiện c1/warehouse-01/address-synthetic; nhiều actor/source chỉ có ID. Ngày hiệu lực và kỳ kế toán còn ISO. Có mã có ích để đối chiếu nhưng thiếu tên nghiệp vụ phía trước.','DTO reference được render nguyên dạng; chưa resolve tên qua read model có quyền. Date-only chưa qua formatter riêng.','Dùng tên đã có và được phép đọc + mã phụ/copy. Nếu contract chỉ có ID thì ghi rõ Mã..., không suy ra danh tính. Date-only định dạng tiếng Việt không chuyển UTC làm lệch ngày.','Không N+1 theo từng row; dùng cache/read model/lookup bounded được contract cho phép. Không fetch danh tính thiếu quyền. Ngày giữ đúng date-only và timezone.'],
 ['UX10','P2','Accessible name đã đo','Nhiều bảng cùng tên Dữ liệu','R09,R12,R17,R19,R21,R23,R24,R25,R26,R28,R32,R34,R35,R37,R38,R40,R41,R42,R43,R44,R45,R46,R47,R48,R49,R50,R51,R54','shared/ui/components.tsx:122','30/38 bảng quan sát có aria-label Dữ liệu. R44 và R50 có hai bảng cùng tên. Heading nhìn thấy giúp mắt nhưng không đổi accessible name của table/scroll region.','DataTable có default generic; consumer không truyền label nghiệp vụ.','Truyền label rõ cho từng bảng; shared owner đảm bảo table và vùng cuộn cùng ngữ cảnh. Giữ horizontal scrolling được phép cho bảng dữ liệu.','R44 có Nhà cung cấp/Báo giá sản phẩm; R50 có Công nợ/Kỳ kế toán. Keyboard cuộn và focus rõ; không tuyên bố speech PASS khi chưa nghe screen reader.'],
 ['UX11','P2','Cải tiến từ thiết kế hiện có','Phân trang thiếu đường lùi trực tiếp','Các route dùng Pager','shared/ui/components.tsx:242','Pager có Đầu danh sách và Trang tiếp, không có Trang trước hoặc thông tin vùng đang xem. Đây là hạn chế usability, không chứng minh cursor API sai.','UI tối thiểu cho cursor chỉ giữ next/current; người dùng phải về đầu hoặc dùng browser history.','Có thể giữ stack cursor đã đi qua theo bộ lọc/scope và nút Trang trước. Hiển thị số hàng đã tải/hiện có; không bịa page count hoặc total.','Thay filter xóa stack; refresh deep-link có fallback rõ; cuối trang disable next; không thêm API offset/sort không có trong contract.'],
 ['UX12','P2','Cải tiến form từ UI/source','Form cần chỉ dẫn và thời điểm báo lỗi rõ','R03,R05,R09,R18,R33,R35,R40,R48','workspace/index.tsx:75,122,206; finance/index.tsx:240','R35 vừa mở khi unconfigured đã có trường đỏ. R03 timezone là mã tự nhập, lỗi Intl trả thẳng ErrorNotice. Ngôn ngữ R33 cho nhập locale nhưng app chỉ hỗ trợ vi. Một số filter mặc định là ô trống thay vì Tất cả.','Validation tính ngay không xét touched/submit; cấu hình format và ngôn ngữ UI không được giải thích riêng.','Trạng thái chưa cấu hình dùng hint trung tính; lỗi sau tương tác/submit. Timezone có mẫu/lookup hợp lệ, lỗi tiếng Việt. Làm rõ locale dùng định dạng hay UI; ghi đúng chỉ hỗ trợ vi. Giữ giới hạn contract.','Trước nhập không báo người dùng làm sai; dữ liệu sai vẫn chặn request. Lỗi tại trường, focus lỗi đầu; rỗng/null và default filter có ý nghĩa rõ.'],
 ['UX13','P2','Cải tiến được xác nhận từ source','Phản hồi lưu chưa thống nhất','R12,R32,R44; rà các editor/dialog còn lại','catalog/index.tsx:185; workspace/index.tsx:167','Shop settings có success role=status; save danh mục/nhân sự chủ yếu đóng dialog và invalidate. Chưa kiểm lưu thực tế trong audit này; không khẳng định request đã mất hoặc lưu sai.','Consumer tự viết xử lý completion; shared command bảo vệ kỹ thuật nhưng không sở hữu lời phản hồi theo tác vụ.','Dùng inline success/role=status tại nơi liên quan, nêu đối tượng và kết quả thật. Nếu còn edit trong lúc save, phản hồi phần đã gửi và giữ phần chưa lưu.','Success chỉ sau outcome xác định; lỗi/unknown không báo thành công. Không thêm global toast hoặc thư viện mới trái convention. Geometry pending chưa đo nên chỉ là điểm cần kiểm.'],
 ['UX14','P2','Cải tiến empty/recovery đã quan sát','Màn rỗng chưa dẫn bước tiếp theo','R14,R25,R28,R36,R45,R49; các danh sách có no-match','shared/ui/components.tsx:122,142','R25/R28/R45/R49 hiện Chưa có dữ liệu phù hợp ở default không filter; R14/R36 missing-job có thông báo chung và không có link về luồng tạo. Không xem missing-job là thiếu route.','Shared DataTable chỉ có empty text mặc định; consumer ít phân biệt first-use/no-match/không có quyền/đối tượng không còn.','Copy theo tình huống: chưa có phản hồi, chưa chạy đánh giá, chưa có đề nghị, chưa nhập sao kê. Có CTA/đường quay lại hợp lệ đúng quyền. Unknown outcome dùng recovery riêng hiện có.','Empty có lý do và bước tiếp theo, khác lỗi transport. Không gợi ý tạo dữ liệu ngoài quyền; không lộ sự tồn tại tài nguyên ở shop khác.'],
 ['UX15','P2','Lỗi đọc nhãn đã đo','Nhãn DetailLine bị co và tách chữ','R06; rà các consumer DetailLine','shared/ui/components.tsx:471','Ở viewport1280x720, nhãn Kênh trong bối cảnh Inbox rộng30.484px, cao42px/2 dòng dù chỉ một từ. Giá trị Trang Facebook mẫu · Studio rộng173.516px. Hai phần cùng flex-shrink:1 và overflow-wrap:anywhere.','Shared DetailLine chỉ minWidth0 cho cả caption/value, không có giới hạn theo vai trò; nội dung dài ăn phần nhãn. Không overflow không đồng nghĩa dễ đọc.','Shared owner giữ vùng caption tối thiểu theo nội dung, cho value wrap; chuyển thành hai dòng khi phần dùng thực sự hẹp. Dùng quy định geometry có giới hạn, không pixel workaround từng màn.','Kênh không bị tách giữa chữ ở bố cục hiện tại; caption dài/value dài đều đọc được khi320px và zoom. Không gây overflow hoặc giảm target44px. Các consumer khác chỉ là phạm vi cần rà, chưa khẳng định đều lỗi.'],
].map(([id,priority,classification,title,routes,sourceRef,observation,rootCause,recommendation,acceptance])=>({id,priority,classification,title,routes:routes.split(','),sourceRef,observation,rootCause,recommendation,acceptance}));
const notes=[
 ['R01','UX07,UX08','Giữ login/OIDC boundary; thay lời giải thích localStorage bằng thông tin phiên người dùng cần biết.'],
 ['R02','UX06,UX07','Việt hóa vai trò owner; card chọn shop hiện đúng. Tìm shop khi danh sách lớn là tùy chọn, chưa có bằng chứng chậm.'],
 ['R03','UX04,UX08,UX12','Bổ sung bảo vệ nháp, hướng dẫn timezone và lỗi tại trường; giữ tiền tệ đã chốt trước giao dịch.'],
 ['R04','UX07,UX08','Cân nhắc đưa KPI/việc cần xử lý lên sớm hơn hero; đây là tối ưu phân cấp, không lỗi spacing.'],
 ['R05','UX06,UX07,UX11,UX12','Hiện Tất cả ở filter; rõ kết quả/tìm kiếm; giữ bố cục master-detail và quyền kênh.'],
 ['R06','UX06,UX08,UX09,UX15','Việt hóa trạng thái tin; giữ nhãn Kênh không tách chữ; tách preview dài khỏi khung xử lý; media gửi thật đang thiếu contract.'],
 ['R07','UX05,UX10,UX11','Rà đường về sau hồ sơ giữ q/cursor; tối ưu cột liên hệ theo quyền, không bỏ redaction.'],
 ['R08','UX05,UX06,UX09','Sửa completed/draft và sự kiện giao; giữ giới hạn10 bản xem nhanh và đường tới lịch sử.'],
 ['R09','UX05,UX10,UX11,UX12','Giữ filter khi về từ chi tiết; tên bảng Sản phẩm; bộ lọc mặc định rõ nghĩa.'],
 ['R10','UX07,UX08,UX12','Breadcrumb Tạo sản phẩm; hướng dẫn SKU/giá/ảnh theo tác vụ. Header/save sticky chỉ cân nhắc sau kiểm zoom.'],
 ['R11','UX03,UX05,UX09','Header có tên/SKU; dialog ngừng bán có đối tượng; giữ draft/version/ảnh khi refetch.'],
 ['R12','UX03,UX10,UX13','Dialog nêu tên danh mục, nhãn Ngừng dùng; feedback lưu inline. Cây phân cấp là tùy chọn nếu danh mục sâu.'],
 ['R13','UX06,UX08,UX14','Giữ tải→ánh xạ→kiểm tra→xác nhận; Việt hóa tên trường ở UI, giữ header CSV kỹ thuật. Nháp mapping cần rà guard khi triển khai.'],
 ['R14','UX07,UX14','Đã mở error missing-job. Cần mở job hợp lệ khi kiểm sửa; lỗi có đường về Nhập dữ liệu. Không đánh dấu success đã kiểm.'],
 ['R15','UX02,UX09,UX10','Tách Còn/Sắp hết/Hết khỏi Bị chặn; giữ snapshot và tồn cách ly riêng; tên kho theo lookup hợp lệ.'],
 ['R16','UX02,UX06,UX09','receipt phải Nhập kho; actor/biến thể có tên được quyền đọc + mã đối chiếu.'],
 ['R17','UX05,UX09,UX10,UX11','Tên khách thay ID khi có read model; thêm filter status chỉ nếu API cho phép; không gộp ba trạng thái đơn/giao/tiền.'],
 ['R18','UX07,UX08,UX12','Breadcrumb Tạo đơn; thay tên listCustomers/listProducts bằng trợ giúp nghiệp vụ; địa chỉ/kho hiện mới preview.'],
 ['R19','UX03,UX05,UX09,UX10','Tên khách, kho, địa chỉ rõ; confirm Hủy đơn có mã. Giữ lấy báo giá/xác nhận như hai bước riêng.'],
 ['R20','UX07,UX08,UX09','Giữ dòng tiền khác doanh thu; có thể thêm preset kỳ hợp lệ. Chart xu hướng cần API bucket, không cộng dòng trang.'],
 ['R21','UX03,UX09,UX10,UX11','Chứng từ nguồn có nhãn + mã; rà đảo phiếu với số tiền/đối tượng rõ, giữ lịch sử.'],
 ['R22','UX07,UX08,UX09','Giữ completeness và khoản chưa đủ dữ liệu; rút technical copy, giải thích cấu phần khi cần.'],
 ['R23','UX05,UX06,UX08,UX10','manual thành Nhập thủ công; nguồn kiến thức giữ ở đầu. Preview/schema giá không chiếm trọng tâm đọc/duyệt nguồn.'],
 ['R24','UX03,UX05,UX09,UX10','Duyệt/xuất bản/ngừng dùng nêu tên và version; reviewer có nhãn; giữ tách revision.'],
 ['R25','UX01,UX10,UX14','Sửa CTA dẫn tới đây; empty hướng dẫn tạo góp ý từ hội thoại; quyền review vẫn do contract.'],
 ['R26','UX06,UX08,UX09,UX10','Việt hóa trợ giúp requireHumanOrderConfirmation; tên kết nối thay ai-01 nếu được đọc; giữ active/draft riêng.'],
 ['R27','UX07,UX09,UX12','Mã khách optional có lookup được quyền đọc hoặc ví dụ rõ; kết quả có nguồn/cảnh báo. Không nhận test mock là chất lượng AI thật.'],
 ['R28','UX07,UX10,UX14','Empty Chưa chạy đánh giá và CTA đúng quyền; kết quả nhấn cấu hình/bộ test/version đã chạy.'],
 ['R29','UX03,UX06,UX08','Capability text thành Văn bản; ngắt kết nối nêu Page; giữ cảnh báo demo/OAuth chưa thật.'],
 ['R30','UX03,UX06,UX08','Tên capability tiếng Việt và hỗ trợ/chưa xác định; xóa nêu kết nối; card đã sử dụng chiều rộng phù hợp.'],
 ['R31','UX07,UX08,UX09','Thay getReportSummary/listJobs bằng phạm vi báo cáo dễ hiểu; giữ ngày/timezone và trạng thái file do API.'],
 ['R32','UX03,UX09,UX10,UX13','Thu hồi nêu người/vai trò; danh tính chỉ theo DTO hợp lệ; feedback mời/cập nhật rõ.'],
 ['R33','UX01,UX07,UX08,UX12','Sửa link feedback; làm rõ locale không phải hứa đa ngôn ngữ; bỏ copy AI lập trình khỏi tác vụ shop.'],
 ['R34','UX06,UX08,UX09,UX10','Friendly action/resource summary + mã chẩn đoán; actor không suy ra là bot nếu DTO thiếu.'],
 ['R35','UX08,UX10,UX12,UX14','Chưa cấu hình không báo đỏ như đã nhập sai; giữ step-up/privacy/legal chưa xác minh. Consent/opt-out thật thiếu contract.'],
 ['R36','UX07,UX14','Đã kiểm missing-job; cần job hợp lệ/expired/unknown khi sửa. Có đường về báo cáo/import, không thử lại lệnh mù.'],
 ['R37','UX06,UX08,UX09,UX10','Hiển thị chủ việc/lý do blocker dễ hiểu; filter ngoại lệ hiện chỉ page đã tải phải giữ nhãn đúng.'],
 ['R38','UX03,UX06,UX08,UX10','Queue lên trước preview; consumed và action code có tên; đối chiếu đúng phiên bản/hạn và không cấp ủy quyền giả.'],
 ['R39','UX06,UX09,UX11','in_app thành Trong ứng dụng; phân biệt đã gửi/đã đọc/đã nhận việc. Bulk đọc cần contract riêng nếu chưa có.'],
 ['R40','UX03,UX08,UX12','Thu hồi nêu thiết bị; lịch trực/recipient có ví dụ và feedback; giữ mock đăng ký không xin quyền OS thật.'],
 ['R41','UX09,UX10,UX11','Tên người nhận việc và SKU rõ; bước lấy/kiểm/đóng gói giữ riêng. Không cần tạo route mới nếu dialog đủ tác vụ.'],
 ['R42','UX03,UX08,UX09,UX10','Bảng vận đơn trước preview; vẫn giữ phí báo giá/thực tế riêng; handover/status dialog có identity.'],
 ['R43','UX06,UX09,UX10','inspected thành Đã kiểm nhận; diễn đạt received theo hàng hoàn; giữ cách ly/nghĩa vụ hoàn tiền riêng.'],
 ['R44','UX03,UX09,UX10,UX13','Hai table name khác nhau; báo giá có SKU/tên hợp lệ; duyệt/tạm dừng có đối tượng và feedback lưu.'],
 ['R45','UX06,UX10,UX14','Empty phân biệt chưa đánh giá/không có đề nghị; rule theo SKU rõ nghĩa; không tự gửi vượt hạn mức.'],
 ['R46','UX03,UX09,UX10','Đơn mua có tham chiếu dễ đọc; modal chi tiết đủ không cần thêm trang. Gửi unknown giữ recovery riêng.'],
 ['R47','UX03,UX09,UX10','Giữ dialog ghi nhận đã có receipt.id và lượng đạt/hỏng; tên table/nguồn rõ. Không tính hàng hỏng vào bán được.'],
 ['R48','UX09,UX10,UX12','Date-only vi; sơ đồ tài khoản thật chưa có API; lỗi dòng sau touched/submit và tổng nợ/có rõ.'],
 ['R49','UX09,UX10,UX14','Empty theo tab ngân hàng/COD/chênh lệch; dẫn nhập hoặc chọn chứng từ; không tự khẳng định đã khớp.'],
 ['R50','UX02,UX09,UX10','Kỳ open thành Đang mở; ngày date-only, tên đối tác; hai table names riêng. Khóa kỳ nêu kỳ và điều kiện còn thiếu.'],
 ['R51','UX03,UX06,UX08,UX09','Tool/budget có nhãn nghiệp vụ; người chịu trách nhiệm; pause/resume nêu vai trò và tác động.'],
 ['R52','UX03,UX06,UX08','Bản tin/health tách vai trò đọc; chẩn đoán kỹ thuật disclosure; giữ Chưa xác minh cho provider/worker/production.'],
 ['R53','UX06,UX08,UX09','Thay getMarketingSummary bằng giới hạn báo cáo dễ hiểu; chart có bảng đã tốt. Filter kỳ cần API, không tự thêm.'],
 ['R54','UX06,UX09,UX10','question thành Câu hỏi; loại/status/người phụ trách rõ. SLA/priority chỉ bổ sung sau contract; không hứa hoàn tiền tự động.'],
];
if(notes.length!==54||new Set(notes.map(x=>x[0])).size!==54)throw Error('Incomplete notes');
fs.writeFileSync(path.join(dir,'findings.json'),JSON.stringify({scope:'Audit recommendations, not a replacement implementation tracker',findings},null,2)+'\n');
const esc=s=>String(s).replaceAll('|','\\|').replaceAll('\n',' ');
const matrix='# Ma trận rà UI/UX từng màn — 2026-10-09\n\n54 route /16 module có binding source. Mỗi dòng đối chiếu code, DOM live và viewport mặc định1280x720. R14/R36 mới mở trạng thái missing-job; không chứng minh nhánh success. Các mã UX liên kết báo cáo, không cập nhật trạng thái tracker.\n\n| Route | Màn / module | Có sẵn theo code | Cần sửa / tối ưu | Nhóm | Bằng chứng |\n|---|---|---|---|---|---|\n'+notes.map(([id,ids,note])=>{let r=source.routes.find(x=>x.id===id);let target=path.resolve(dir,'../..',r.entry.file).replaceAll('\\','/');return `| ${id} | ${esc(r.title)} / ${r.module} | ${esc(r.content)} | ${esc(note)} | ${ids} | [viewport](viewport-${id}.png); [source](${target}:${r.entry.line}) |`;}).join('\n')+'\n\nCác cải tiến P3 tùy chọn: nhất quán icon điều hướng theo loại tác vụ; ưu tiên cột nhận dạng/hành động khi cuộn ngang; preset khoảng ngày; chia nhóm form dài theo workflow. Cần số liệu task/time-on-task trước khi chọn virtualization, bulk actions, dashboard chart mới hoặc phân trang khác. Không có bằng chứng runtime trong audit này để kết luận cần tối ưu thuật toán/render toàn ứng dụng.\n';
fs.writeFileSync(path.join(dir,'SCREEN_MATRIX.md'),matrix);
const detailed=findings.map(f=>`## ${f.id} — ${f.priority} — ${f.title}\n\n**Phân loại:** ${f.classification}. **Ảnh hưởng:** ${f.routes.join(', ')}.\n\n**Bằng chứng:** ${f.observation}\n\n**Owner source:** ${f.sourceRef}.\n\n**Nguyên nhân:** ${f.rootCause}\n\n**Đề xuất:** ${f.recommendation}\n\n**Điều kiện nghiệm thu sau sửa:** ${f.acceptance}\n`).join('\n');
fs.writeFileSync(path.join(dir,'FINDINGS.md'),'# Phát hiện UI/UX chi tiết\n\n'+detailed);
console.log(JSON.stringify({routes:notes.length,findings:findings.length,priorities:findings.reduce((a,f)=>(a[f.priority]=(a[f.priority]||0)+1,a),{}),tableNames:{generic:live.flatMap(x=>x.tables).filter(x=>x.label==='Dữ liệu').length,total:live.flatMap(x=>x.tables).length},documentTitleCount:summary.uniqueDocumentTitles.length}));
