#!/usr/bin/env node
/** Static consistency only. Does not start or certify the application. */
import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';import {fileURLToPath} from 'node:url';import {spawnSync} from 'node:child_process';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..'),read=p=>JSON.parse(fs.readFileSync(path.join(root,p),'utf8')),sha=b=>crypto.createHash('sha256').update(b).digest('hex');
const errors=[],checks=[];const check=(name,ok,detail='')=>{checks.push({name,status:ok?'PASS':'FAIL',detail});if(!ok)errors.push(name+': '+detail);};
const plan=read('execution/plan.json'),features=read('contracts/feature-catalog.json').features,routes=read('contracts/route-manifest.json').routes,o=read('contracts/openapi.json'),perms=read('contracts/permission-catalog.json'),scenario=read('fixtures/acceptance-scenarios.json');
check('Universal file preserved byte-for-byte',sha(fs.readFileSync(path.join(root,'AI_RULES.md')))===read('execution/universal-source.json').sha256);
const p=spawnSync(process.execPath,[path.join(root,'scripts/progress.mjs'),'validate'],{encoding:'utf8'});check('Tracker structure and locked plan',p.status===0,p.stderr.trim());
const ops=[];for(const [url,methods]of Object.entries(o.paths))for(const [method,a]of Object.entries(methods))if(a?.operationId)ops.push({id:a.operationId,path:url,method});
const opSet=new Set(ops.map(x=>x.id)),permSet=new Set(perms.permissions.map(x=>x.id)),taskSet=new Set(plan.tasks.map(x=>x.id)),featSet=new Set(features.map(x=>x.id)),routeSet=new Set(routes.map(x=>x.id));
check('Unique operation IDs',opSet.size===ops.length);check('64 unique approved feature IDs',featSet.size===64);check('Unique route IDs',routeSet.size===routes.length);
function refs(x){if(!x||typeof x!=='object')return;if(x.$ref){let val=o;try{if(!x.$ref.startsWith('#/'))throw new Error('external reference');for(const seg of x.$ref.slice(2).split('/'))val=val[seg.replace(/~1/g,'/').replace(/~0/g,'~')];if(val===undefined)throw new Error('missing');}catch{errors.push('Unresolved $ref '+x.$ref);}}Object.values(x).forEach(refs);}
const before=errors.length;refs(o);check('All OpenAPI schema refs resolve',before===errors.length);
for(const r of routes){check(r.id+' operation IDs exist',[...(r.readOperations||[]),...(r.actions||[]).map(a=>a.operationId)].every(x=>opSet.has(x)));check(r.id+' permission IDs exist',[r.readPermission,...(r.actions||[]).map(a=>a.permission)].filter(Boolean).every(x=>permSet.has(x)));}
for(const t of plan.tasks){check(t.id+' read-first paths exist',t.readFirst.every(p=>fs.existsSync(path.join(root,p))));check(t.id+' known features',t.featureIds.every(f=>featSet.has(f)));check(t.id+' exactly five substantive steps',t.implementationSteps.length===5&&t.implementationSteps.every(s=>s.action.length>30));}
for(const f of features){check(f.id+' maps to implementation task',f.taskIds.length>0&&f.taskIds.every(t=>taskSet.has(t)));check(f.id+' maps to route',f.routeIds.length>0&&f.routeIds.every(r=>routeSet.has(r)));}
for(const [role,p]of Object.entries(perms.rolePresets))check('Role '+role+' permissions',p.every(x=>permSet.has(x)));
check('Schema Permission enum matches catalog',JSON.stringify([...o.components.schemas.Permission.enum].sort())===JSON.stringify([...permSet].sort()));
check('No v1 fulfilment/login write retained',!opSet.has('fulfillOrder')&&!opSet.has('login'));
check('Old archive explicitly nonactive',fs.readFileSync(path.join(root,'reference/README.md'),'utf8').includes('1.1'));
const gold=read('fixtures/finance-golden.json');const bal={};for(const j of gold.journals){let d=0n,c=0n;for(const l of j.debits){d+=BigInt(l.amount);bal[l.account]=(bal[l.account]||0n)+BigInt(l.amount);}for(const l of j.credits){c+=BigInt(l.amount);bal[l.account]=(bal[l.account]||0n)-BigInt(l.amount);}check('Golden journal '+j.id+' balanced',d===c);}
check('Golden closing bank',String(bal.Bank)===gold.expectedAfterSale.bank);check('Golden inventory',String(bal.InventoryWarehouse)===gold.expectedAfterSale.inventory);check('Golden transit zero',bal.InventoryTransit===0n);check('Golden COD receivable zero',bal.CarrierCODReceivable===0n);check('Golden AP zero',bal.SupplierPayable===0n);check('Golden profit',String(-bal.Sales-bal.COGS-bal.CarrierFees)===gold.expectedAfterSale.profit);
check('Prototype token source unchanged',fs.readFileSync(path.join(root,'design/tokens.css'),'utf8')===fs.readFileSync(path.join(root,'prototype/src/tokens.css'),'utf8'));
const report={scope:'KIT_STATIC_CONSISTENCY_NOT_APPLICATION_VERIFICATION',generatedAt:new Date().toISOString(),counts:{features:features.length,routes:routes.length,operations:ops.length,schemas:Object.keys(o.components.schemas).length,permissions:perms.permissions.length,tasks:plan.tasks.length,checkpoints:plan.tasks.reduce((a,t)=>a+t.implementationSteps.length,0)},checks,total:checks.length,passed:checks.filter(x=>x.status==='PASS').length,errors};fs.mkdirSync(path.join(root,'evidence'),{recursive:true});fs.writeFileSync(path.join(root,'evidence/kit-validation.json'),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify({scope:report.scope,...report.counts,totalChecks:report.total,passed:report.passed,errors},null,2));if(errors.length)process.exitCode=1;
