/* Deterministic, in-memory review model ONLY. Real invariants belong in the backend. */
'use strict';
BSDemo.v2=(()=>{
 const D=BSDemo.domain;
 const check=(c,m)=>{if(!c)throw new Error(m)};
 const sum=ls=>ls.reduce((n,l)=>n+BigInt(l.amount),0n);
 function init(s){if(s.ops)return s.ops;s.ops={seq:20,prep:[],notifications:[],shipments:[],pos:[],approvals:[],journals:[],payables:[],returns:[],suppliers:[{id:'SUP-01',name:'Xưởng May An Bình (mẫu)',leadDays:5,contact:'Đầu mối nhà cung cấp mẫu',status:'approved'}],policies:{push:true,telegram:true,reminderMinutes:5,quiet:'22:00–07:00',autobuy:false},devices:[{id:'DEVICE-01',name:'Điện thoại chủ shop',channel:'Web Push',status:'simulated'}],agents:{sales:true,warehouse:true,accountant:true,supervisor:true},period:'open',periodSnapshot:null};return s.ops;}
 const order=(s,id)=>s.orders.find(o=>o.id===id)||(()=>{throw new Error('Không tìm thấy đơn trong shop đang mở.')})();
 function journal(s,ref,label,debits,credits){const v=init(s);if(v.journals.some(j=>j.ref===ref))return;check(sum(debits)===sum(credits),'Bút toán không cân bằng.');v.journals.unshift({id:'JE-'+(++v.seq),ref,label,debits,credits,date:'2026-09-29'});}
 function ensure(s){const v=init(s);for(const o of s.orders){if(o.state==='confirmed'&&o.fulfillment==='unfulfilled'&&!v.prep.some(p=>p.orderId===o.id)){v.prep.push({id:'PREP-'+o.id,orderId:o.id,state:'queued',owner:null});v.notifications.unshift({id:'NOTIF-'+o.id,orderId:o.id,channel:'Web Push',providerStatus:'accepted_mock',ack:false,opened:false,attempts:1});}}
  for(const p of v.prep){const o=order(s,p.orderId);if(o.state==='cancelled'){p.state='cancelled';v.notifications.filter(n=>n.orderId===o.id).forEach(n=>n.cancelled=true);}}return v;}
 function claim(s,id,actor){const v=ensure(s),p=v.prep.find(p=>p.orderId===id);check(p&&p.state==='queued','Đơn đã có người nhận, bị hủy hoặc chưa đủ điều kiện.');p.state='claimed';p.owner=actor;v.notifications.filter(n=>n.orderId===id).forEach(n=>{n.ack=true;n.opened=true;});return p;}
 function advance(s,id,target){const v=ensure(s),p=v.prep.find(p=>p.orderId===id);check(p,'Chưa có việc chuẩn bị.');const o=order(s,id);check(o.state==='confirmed','Đơn không còn hiệu lực.');const next={claimed:'picked',picked:'packed',packed:'handed_over'};check(next[p.state]===target,'Không thể bỏ qua bước nhận/lấy/đóng gói/bàn giao.');if(target==='handed_over'){check(v.period==='open','Kỳ đã khóa.');const costSnapshot=o.lines.map(l=>s.products.find(p=>p.id===l.productId).cost);D.command(s,id,'dispatch');o.lines.forEach((l,i)=>l.unitCost=costSnapshot[i]);const transfer=D.cost(o).toString();journal(s,'TRANSIT-'+id,'Bàn giao hàng '+id,[{account:'InventoryTransit',amount:transfer}],[{account:'InventoryWarehouse',amount:transfer}]);v.shipments.push({id:'SHIP-'+id,orderId:id,tracking:'DEMO-'+id,state:'in_transit',carrier:'Đơn vị giao hàng mẫu'});o.paymentMethod='cod';}p.state=target;return p;}
 function deliver(s,id){const v=ensure(s),ship=v.shipments.find(x=>x.orderId===id);check(ship&&ship.state==='in_transit','Đơn chưa bàn giao hoặc đã ghi giao hàng.');check(v.period==='open','Kỳ đã khóa; mở lại có lý do trước khi ghi nghiệp vụ.');const o=order(s,id);ship.state='delivered';o.fulfillment='fulfilled';o.payment=o.payment==='paid'?'paid':'cod_collected';if(o.payment==='paid')o.state='completed';o.version++;const total=D.total(o).toString(),cost=D.cost(o).toString();journal(s,'SALE-'+id,'Giao thành công '+id,[{account:o.payment==='paid'?'Cash clearing':'COD receivable',amount:total}],[{account:'Sales revenue',amount:total}]);journal(s,'COGS-'+id,'Giá vốn '+id,[{account:'COGS',amount:cost}],[{account:'InventoryTransit',amount:cost}]);return o;}
 function settleCOD(s,id,fee){const v=init(s),o=order(s,id);check(v.period==='open','Kỳ đã khóa.');check(o.payment==='cod_collected','Chỉ đối soát COD đã thu bởi đơn vị giao hàng, chưa chuyển shop.');const f=D.money(fee),total=D.total(o);check(f<=total,'Phí không thể lớn hơn số COD.');o.payment='paid';o.state='completed';o.settledNet=(total-f).toString();o.version++;if(f>0n)s.expenses.push({id:'FEE-'+id,date:'2026-09-29',type:'operating',amount:f.toString(),note:'Phí giao hàng đối soát '+id,category:'Vận chuyển'});journal(s,'SETTLE-'+id,'Đối soát COD '+id,[{account:'Bank',amount:(total-f).toString()},{account:'Delivery fee',amount:f.toString()}],[{account:'COD receivable',amount:total.toString()}]);return o;}
 function suggestions(s){const v=init(s);return s.products.filter(p=>p.active&&D.available(p)<=p.threshold).map(p=>{const pending=v.pos.filter(po=>po.productId===p.id&&!['cancelled','received'].includes(po.state)).reduce((a,po)=>a+po.quantity-po.received,0);return {p,pending,quantity:Math.max(0,p.threshold*3-D.available(p)-pending),target:p.threshold*3};});}
 function createPO(s,productId,qty){const v=init(s);check(v.period==='open','Kỳ đã khóa.');const p=s.products.find(p=>p.id===productId);check(p,'Không có sản phẩm.');const q=D.quantity(qty),r=suggestions(s).find(r=>r.p.id===productId);check(r&&q<=r.quantity,'Lượng nhập vượt đề nghị hiện hành hoặc đã có đơn mua đang mở.');const po={id:'PO-'+(++v.seq),productId,supplierId:v.suppliers[0].id,quantity:q,received:0,unitCost:p.cost,state:'pending_approval',version:1};v.pos.unshift(po);v.approvals.unshift({id:'APR-'+po.id,poId:po.id,state:'pending',version:po.version,snapshot:JSON.stringify([po.productId,po.quantity,po.unitCost,po.supplierId,po.version])});return po;}
 function decide(s,id,accept){const v=init(s),a=v.approvals.find(a=>a.id===id);check(a&&a.state==='pending','Yêu cầu đã được xử lý.');const po=v.pos.find(p=>p.id===a.poId);check(a.snapshot===JSON.stringify([po.productId,po.quantity,po.unitCost,po.supplierId,po.version]),'Nội dung đã thay đổi; phê duyệt cũ không còn hiệu lực.');a.state=accept?'approved':'rejected';po.state=accept?'approved':'cancelled';return po;}
 function sendPO(s,id){const v=init(s),p=v.pos.find(p=>p.id===id);check(p&&p.state==='approved','Cần phê duyệt còn hiệu lực trước gửi đơn mua.');p.state='sent';return p;}
 function receive(s,id,qty){const v=init(s),po=v.pos.find(p=>p.id===id);check(v.period==='open','Kỳ đã khóa.');check(po&&['confirmed','part_received'].includes(po.state),'Nhà cung cấp phải xác nhận đơn trước khi nhận.');const q=D.quantity(qty);check(q<=po.quantity-po.received,'Số nhận lớn hơn số còn chờ.');const p=s.products.find(p=>p.id===po.productId),amount=BigInt(po.unitCost)*BigInt(q);p.cost=((BigInt(p.cost)*BigInt(p.onHand)+amount)/BigInt(p.onHand+q)).toString();p.onHand+=q;po.received+=q;po.state=po.received===po.quantity?'received':'part_received';po.version++;s.movements.unshift({id:'RCV-'+(++v.seq),productId:p.id,change:q,reason:'Nhận hàng '+po.id,date:'2026-09-29'});const ref='RECEIPT-'+po.id+'-'+po.received;v.payables.unshift({id:ref,poId:po.id,amount:amount.toString(),state:'unpaid'});journal(s,ref,'Nhận hàng '+po.id,[{account:'InventoryWarehouse',amount:amount.toString()}],[{account:'Accounts payable',amount:amount.toString()}]);return po;}
 function requestReturn(s,id,qty){const v=init(s),o=order(s,id);check(o.fulfillment==='fulfilled'&&o.state!=='returned','Cần đơn đã giao, còn hiệu lực.');check(!v.returns.some(r=>r.orderId===id&&r.state!=='rejected'),'Demo chỉ cho một yêu cầu đang xử lý trên đơn.');const l=o.lines[0],q=D.quantity(qty);check(q<=l.quantity,'Số trả vượt số mua ở dòng đầu.');const r={id:'RET-'+(++v.seq),orderId:id,productId:l.productId,quantity:q,state:'awaiting_inspection',amount:(BigInt(l.unitPrice)*BigInt(q)).toString()};v.returns.unshift(r);return r;}
 function closePeriod(s){const v=ensure(s);check(v.period==='open','Kỳ đã khóa.');check(!s.orders.some(o=>o.payment==='cod_collected'),'Còn COD chưa đối soát.');check(!v.pos.some(p=>!['received','cancelled'].includes(p.state)),'Còn đơn mua chưa hoàn tất.');check(!v.returns.some(r=>!['rejected','resolved'].includes(r.state)),'Còn đổi trả chưa xử lý.');check(!v.approvals.some(a=>a.state==='pending'),'Còn phê duyệt chưa xử lý.');v.period='closed';v.periodSnapshot=D.tally(s).profit.toString();}
 return {init,ensure,claim,advance,deliver,settleCOD,suggestions,createPO,decide,sendPO,receive,requestReturn,closePeriod,journal};
})();
if(typeof module!=='undefined')module.exports=BSDemo.v2;
