import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import {execFileSync} from 'node:child_process';
import {validateUiEvidence} from '../../scripts/validate-ui-evidence.mjs';
const output=import.meta.dirname,root=path.resolve(output,'../..'),repo=path.dirname(root),prefix='evidence/frontend-spacing-density-20261009/';
const read=f=>JSON.parse(fs.readFileSync(f,'utf8')),hash=f=>crypto.createHash('sha256').update(fs.readFileSync(f)).digest('hex'),rel=f=>path.relative(repo,f).replaceAll('\\','/'),assert=(v,m)=>{if(!v)throw Error(m);};
const fingerprints={},checks=[],records={};
function capture(file){const f=path.resolve(root,file);assert(f.startsWith(repo+path.sep)&&fs.existsSync(f),'Missing '+file);fingerprints[rel(f)]=hash(f);return f;}
function proof(id,file,description,validate){const f=capture(file),value=read(f);validate(value);checks.push({id,command:'Recorded actual execution/review: '+file,exitCode:0,result:'PASS',expected:description,observed:description,log:{path:rel(f),sha256:hash(f)}});return value;}
const patterns={verify:/Tests\s+181 passed \(181\)/,unit:/Tests\s+181 passed \(181\)/,contracts:/pass 41\s/,layout:/layout-check PASS: 79 source files, 0 finding\(s\), 1 exception\(s\) used/, 'evidence-validator':/pass 11\s/,'source-maps':/pass 16\s/,e2e:/\b624 passed \(/,'built-demo':/\b6 passed \(/,'composer-stability':/\b6 passed \(/};
for(const stage of [...Object.keys(patterns),'imports-clearance-regression','composer-regression','label-focus-regression','variant-regression','label-regression','startup-cache-regression']){
 const pointer=read(path.join(output,stage+'-latest.json')),record=read(path.join(repo,pointer.record)),log=fs.readFileSync(path.join(repo,record.log.path),'utf8');
 assert(!record.exitCode&&!record.sourceDrift.length&&hash(path.join(repo,record.log.path))===record.log.sha256,'Failed/changed '+stage);assert((patterns[stage]||/\b2 passed \(/).test(log),'Incomplete '+stage);
 for(const [file,digest]of Object.entries(record.sourceFingerprints)){assert(hash(path.join(repo,file))===digest,'Stale '+stage+':'+file);fingerprints[file]=digest;}
 if(stage==='verify')assert(log.includes('"passed":88')&&log.includes('Boundary fixtures: PASS 10/10')&&log.includes('"outputs":11,"schemas":283,"operations":210,"routes":54'),'Incomplete verify');
 if(stage==='e2e'){assert(!/\b\d+ failed\b/.test(log),'Full run failed');for(const engine of ['chromium','firefox'])assert(log.split('\n').filter(line=>/^\s*ok\s+\d+/.test(line)&&line.includes('['+engine+']')).length===312,'Engine execution mismatch');}
 records[stage]=record;capture(path.relative(root,path.join(repo,pointer.record)));checks.push({id:stage,command:record.executable+' '+record.args.join(' '),exitCode:0,result:'PASS',expected:'Fresh complete '+stage+' owner suite',observed:'Fresh complete '+stage+' owner suite',log:record.log});
}
const ui=proof('full-ui-binding',prefix+'ui-final-full-coverage.json','250 UI cases in one624-case full run',v=>assert(v.status==='PASS'&&v.fullCases===624&&v.uiCases===250&&v.projects.chromium===125&&v.projects.firefox===125&&hash(path.join(repo,v.fullRecord))===v.fullRecordSha256,'Incomplete UI binding'));
const cold=proof('cold-build',prefix+'clean-artifacts-width-20261009.json','10 actual isolated stages; byte identical repeat artifacts',v=>{assert(v.status==='PASS'&&v.commandRuns.length===10&&v.commandRuns.every(r=>!r.exitCode)&&!v.userEnvLocalCopied&&v.tempWorkspaceRemovedAfterPass,'Cold incomplete');for(const [dir,name]of [['dist','productionRepeat'],['dist-demo','demoRepeat']])for(const f of v.artifacts[name].files)assert(hash(path.join(root,'apps/web',dir,f.path))===f.sha256,'Cold/current artifacts differ');});
proof('cold-cleanup',prefix+'cold-cleanup-current.json','Separate cleanup of the verified owned temporary workspace',v=>{assert(v.status==='PASS'&&v.removed&&v.insideTemporaryRoot&&v.target===cold.isolatedWorkspace&&!fs.existsSync(v.target),'Cold cleanup incomplete');assert(cold.cleanup.sha256===hash(path.join(output,'cold-cleanup-current.json'))&&hash(path.join(repo,v.originalManifest.path))===v.originalManifest.sha256,'Cleanup provenance stale');capture(path.relative(root,path.join(repo,v.originalManifest.path)));});
proof('cold-source',prefix+'cold-source-copy-current.json','Actual copied input bytes match final source',v=>{assert(v.status==='PASS'&&!v.drift.length&&v.copies.length===Object.keys(records.e2e.sourceFingerprints).length&&v.isolatedWorkspace===cold.isolatedWorkspace,'Cold source incomplete');for(const f of v.copies)assert(f.sha256===f.copiedSha256&&hash(path.join(repo,f.path))===f.sha256,'Cold stale');});
proof('environment',prefix+'environment-current.json','6 actual environment/install/setup/doctor/audit commands',v=>{assert(v.runs.length===6&&!v.drift.length&&v.runs.every(r=>!r.exitCode),'Environment incomplete');for(const r of v.runs)assert(hash(path.join(repo,r.log.path))===r.log.sha256,'Environment log stale');});
proof('compiled',prefix+'built-shared-review.json','216 routes and70 focused geometry/axe/keyboard cases',v=>{assert(v.status==='PASS'&&v.observations.length===216&&v.details.length===70&&!v.sourceDrift.length&&!v.artifactDrift.length&&!v.pageErrors.length,'Compiled incomplete');for(const f of v.artifacts){assert(hash(path.join(repo,f.path))===f.sha256,'Artifact stale');fingerprints[f.path]=f.sha256;}for(const [f,h]of Object.entries(v.sourceFingerprints)){assert(hash(path.join(repo,f))===h,'Compiled source stale');fingerprints[f]=h;}for(const row of v.details)capture(path.relative(root,path.join(repo,row.screenshot.path)));});
const native=read(capture(prefix+'native-current.json'));assert(native.status==='PASS'&&native.routeLabelProbeCount===108&&Object.values(native.proofCounts).reduce((a,b)=>a+b,0)===16,'Native scope incomplete');
for(const [file,count]of Object.entries(native.proofCounts))proof('native-'+path.basename(file),file,count+' actual native scenarios PASS',v=>{assert(v.result==='PASS'&&v.scenarios.length===count&&v.scenarios.every(r=>r.result==='PASS'),'Native incomplete');for(const [f,h]of Object.entries(v.sourceSha256)){const absolute=path.resolve(root,f);assert(hash(absolute)===h,'Native stale');fingerprints[rel(absolute)]=h;}for(const scenario of v.scenarios)if(scenario.screenshot){assert(hash(path.join(root,scenario.screenshot.path))===scenario.screenshot.sha256,'Native deep screenshot stale');capture(scenario.screenshot.path);}if(v.routeLabelProbes){assert(v.routeLabelProbes.length===108&&v.routeLabelProbes.every(r=>r.result==='PASS'),'Native labels incomplete');for(const row of v.routeLabelProbes){assert(hash(path.join(root,row.screenshot.path))===row.screenshot.sha256,'Native screenshot stale');capture(row.screenshot.path);}}});
proof('browser-preservation',prefix+'browser-preservation-current.json','Historical bytes preserved by sequential full/built wrappers',v=>assert(v.status==='PASS'&&!v.mismatches.length,'Historical drift'));
proof('domain-publication',prefix+'domain-publication-current.json','Exact generated domain bytes published after browser wrappers',v=>{assert(v.status==='PASS'&&v.produced.sha256===v.target.sha256,'Domain publication incomplete');for(const f of [v.original,v.produced,v.target]){assert(hash(path.join(repo,f.path))===f.sha256,'Domain stale');fingerprints[f.path]=f.sha256;}});
const scope=proof('scope',prefix+'final-scope-review.json','248 before copies verified; all original paths retained; clean whitespace',v=>{assert(v.status==='PASS'&&v.beforeCopies.length===248&&v.beforeCopies.every(r=>r.matchesBaseline)&&!v.unexpected.length&&!v.protectedDrift.length&&!v.missingOriginalPaths.length&&!v.gitDiffCheck.exitCode,'Scope incomplete');capture(path.relative(root,path.join(repo,v.diff.path)));});
proof('preview',prefix+'handoff-demo-current.json','4173 serves exact compiled HTML; seven affected screens inspected',v=>{assert(v.status==='PASS'&&v.statusCode===200&&v.servedHtml===v.expectedHtml&&v.expectedHtml===hash(path.join(root,'apps/web/dist-demo/index.html'))&&!v.pageErrors.length&&v.observations.length===7,'Preview stale');for(const row of v.observations){assert(hash(path.join(repo,row.screenshot.path))===row.screenshot.sha256,'Preview screenshot stale');capture(path.relative(root,path.join(repo,row.screenshot.path)));}});
const pointer=read(path.join(output,'canonical-revalidation-latest.json'));proof('canonical',prefix+pointer.record,'140/140 fresh FE; full product unchanged',v=>assert(v.status.verifiedSteps===140&&v.status.totalSteps===140&&!v.status.stale.length&&!v.status.blocked.length&&!v.fullProductDrift.length,'Canonical incomplete'));
const status=JSON.parse(execFileSync(process.execPath,['scripts/progress.mjs','status'],{cwd:path.join(repo,'botsales-kit'),encoding:'utf8'}));assert(status.verifiedSteps===140&&!status.stale.length&&!status.blocked.length,'Live canonical stale');
const inventory=read(capture(prefix+'inventory-current.json')),adoption=read(capture(prefix+'adoption-current.json')),matrix=read(capture('docs/route-state-role-matrix.json'));
assert(inventory.summary.allRelevantAssigned&&inventory.summary.exhaustiveDiskPartition&&!inventory.unknownFiles.length&&!inventory.runtimeUnresolvedOwnImports.length&&inventory.unresolvedOwnImports.every(v=>v.resolutionClassification&&v.sourceExists),'Inventory unresolved');assert(adoption.summary.routes===54&&adoption.summary.modules===16&&adoption.publicApis.length===28&&!adoption.summary.unresolvedRouteTags,'Adoption incomplete');assert(matrix.routes.length===54&&matrix.summary.routeRoleBrowserMatrix==='PASS'&&matrix.summary.routeMountSmoke==='PASS','Matrix incomplete');
const stateCells=matrix.routes.reduce((n,route)=>n+Object.keys(route.states).length,0);assert(stateCells===432&&matrix.summary.canonicalRouteStates.length===8&&matrix.routes.every(route=>matrix.summary.canonicalRouteStates.every(state=>route.states[state]?.result&&route.states[state].evidence?.length)),'State dispositions incomplete');
const after=proof('paired-routes',prefix+'after.json','216 current loaded routes paired against216 before',v=>{assert(v.status==='PASS'&&v.observations.length===216&&!v.errors.length&&!v.sourceDrift.length,'After incomplete');for(const row of v.observations)assert(hash(path.join(repo,row.screenshot.path))===row.screenshot.sha256,'After screenshot stale');});
proof('paired-comparison',prefix+'paired-route-comparison.json','216 exact route/engine/viewport pairs; measured row/list density',v=>{assert(v.status==='PASS'&&v.pairs.length===216&&hash(path.join(repo,v.before.path))===v.before.sha256&&hash(path.join(repo,v.after.path))===v.after.sha256,'Paired comparison stale');for(const [file,digest]of Object.entries(after.sourceFingerprints))assert(hash(path.join(repo,file))===digest,'Final capture stale:'+file);});
for(const file of ['README.md','AGENTS.md','DESIGN.md','UX-CONTRACT.md','docs/PROJECT_CONTEXT.md','docs/CONTINUE_FRONTEND.md','docs/KNOWN_GAPS.md','docs/FRONTEND_SPACING_STANDARD.md','docs/FRONTEND_UI_IMPROVEMENT_PLAN.md','docs/route-implementation.json','evidence/REPORT.md',...fs.readdirSync(output).filter(f=>/\.(?:mjs|md)$/.test(f)).map(f=>prefix+f),prefix+'route-matrices-refresh-current.json',prefix+'tooling-import-resolution-current.json',prefix+'shared-api-current.json',prefix+'canonical-revalidation-latest.json'])capture(file);
const progress=read(path.join(repo,'botsales-kit/execution/frontend-progress.json'));for(const task of Object.values(progress.tasks))for(const step of Object.values(task.steps))capture('../botsales-kit/'+step.evidence.path);
for(const file of ['AGENTS.md','AI_RULES_PROJECT.md','docs/18_CODING_STANDARDS.md','execution/frontend-plan.json','execution/frontend-command-map.json','execution/frontend-progress.json','execution/frontend-progress-report.json','execution/FRONTEND_PROGRESS.md','IMPLEMENTATION_PLAN.md'])capture('../botsales-kit/'+file);
const baseline=read(path.join(output,'before.json')),start=read(path.join(output,'implementation-start.json'));assert(baseline.status==='PASS'&&baseline.observations.length===216,'Before incomplete');
const baselineFiles=[path.join(output,'before.json'),...scope.beforeCopies.map(v=>path.join(repo,v.copy)),...baseline.observations.map(v=>path.join(repo,v.screenshot.path))];
const cov=(name,count,reason)=>({name,expected:count,observed:count,missing:0,result:'COMPLETE',reason});
const evidence={schemaVersion:1,step:'S19',scope:'Systematic spacing density at Shared owners, all54 route closures in16 modules, operational/reading/form/dialog finite profiles and disclosure; synthetic local Frontend.',recordedAt:new Date().toISOString(),status:'COMPLETE',checks,sourceIdentity:{HEAD:records.e2e.HEAD,inputCount:Object.keys(records.e2e.sourceFingerprints).length,sha256:crypto.createHash('sha256').update(Object.entries(records.e2e.sourceFingerprints).map(([f,h])=>f+':'+h).sort().join('\n')).digest('hex')},coverage:[cov('source-files',inventory.summary.sourceFiles,'Assigned first party source; strict owners, import inventory and gate proof.'),cov('shared-api-exports',28,'Resolved public exports and executed owned render contracts.'),cov('route-mappings',54,'Canonical route bindings.'),cov('rendered-routes',54,'216 default compiled observations plus full route/role smoke; not every business branch.'),cov('slots',28,'All28 public API rendered contracts; finite profile additions and affected owner regression, not every feature callback branch.'),cov('states',stateCells,'Canonical applicable shared/route-specific/N/A dispositions; not432 distinct tests.'),cov('baseline-records',216,'Actual before loaded route capture small/large in two engines.'),cov('native-scenarios',124,'16 deep native plus108 default route label/reflow probes; counts stay separate from full E2E.'),cov('reviewed-input-changes',scope.changed.length,'Changes against preserved dirty baseline.')],baseline:{status:'CAPTURED',capturedAt:baseline.finishedAt,implementationStartedAt:start.at,artifacts:baselineFiles.map(f=>({path:rel(f),sha256:hash(f)})),sourceFingerprints:baseline.sourceFingerprints},sourceFingerprints:fingerprints,knownLimits:['Frontend synthetic local scope only; Backend/provider/staging/production outside scope.','Screen reader speech/broad human conformance/hosted CI NOT_RUN; user acceptance PENDING.','One complete passing full suite; failing/interrupted runs retained without adding targeted passes.','Native methods are actual browser settings; route mount and labels do not prove all conditional states.','Before source copies protect prior dirty work. No commit/push this batch.','Regression protects measured invariants, not every possible future defect.']};
const errors=validateUiEvidence(evidence,repo);assert(!errors.length,errors.join('\n'));fs.writeFileSync(path.join(output,'S19-current-evidence.json'),JSON.stringify(evidence,null,2)+'\n');console.log(JSON.stringify({checks:checks.length,fingerprints:Object.keys(fingerprints).length,FE:'140/140',status:'COMPLETE'}));
