import fs from 'node:fs';
import path from 'node:path';
const root=path.resolve(import.meta.dirname,'../..'), standardFile=path.join(root,'docs/FRONTEND_SPACING_STANDARD.md'), planFile=path.join(root,'docs/FRONTEND_UI_IMPROVEMENT_PLAN.md');
let standard=fs.readFileSync(standardFile,'utf8');
if(!standard.includes('**Phiên bản:** 1.28')||standard.includes('### 4.1. Mật độ theo vai trò'))throw Error('Unexpected policy baseline');
standard=standard.replace('**Phiên bản:** 1.28 · **Ngày:** 07/10/2026','**Phiên bản:** 1.29 · **Ngày:** 09/10/2026');
const rows={
 'page.contentInsetBlock':['16','16','16'], 'page.sectionGap':['16','16','16'], 'page.sectionBefore` / `page.sectionAfter':['16','16','16'],
 'pageHeader.afterGap':['16','16','16'], 'surface.inset':['12','16','16'], 'surface.headerInset':['px/pt 12; pb12','px/pt 16; pb12','px/pt 16; pb12'], 'surface.bodyInsetAfterHeader':['px/bottom 12; top0','px/bottom 16; top0','px/bottom 16; top0'],
 'actions.beforeGap':['16','16','16'], 'grid.gutter':['16','16','16'], 'stats.afterGap':['16','16','16'], 'dashboard.sectionGap':['16','16','16'], 'dashboard.actionTarget':['height ≥44, px12/py8','same','same'],
 'toolbar.inset':['12','12','12'], 'toolbar.controlGap':['8','8','8'], 'table.cellInset':['8 dọc / 12 ngang','như mobile','như mobile'], 'pager.inset':['12','12','12'], 'detail.rowInsetBlock':['8','8','8'], 'detail.valueGap':['12','12','12'],
 'empty.insetBlock':['24','32','32'], 'footer.insetBlock':['8','8','8'], 'shell.demoToolsBefore':['12','12','12'],
 'inbox.paneInset':['12','12','12'], 'inbox.composerInset':['12','12','12'], 'inbox.listInset':['12','12','12'], 'inbox.contextInset':['12','16','16'],
 'report.contextGap':['12','12','12'], 'report.listSurfaceInset':['16 all edges','16 all edges','16 all edges'], 'report.emptyStateInset':['16 all edges','16 all edges','16 all edges'],
};
for(const [role,values]of Object.entries(rows)){
 const needle='| `'+role+'` |', lines=standard.split('\n'), indices=lines.flatMap((line,i)=>line.startsWith(needle)?[i]:[]);
 if(indices.length!==1)throw Error('Policy role must have one canonical row '+role);
 const parts=lines[indices[0]].split('|');for(let i=0;i<3;i++)parts[i+2]=' '+values[i]+' ';lines[indices[0]]=parts.join('|');standard=lines.join('\n');
}
standard=standard.replace('bottom edge owns 16px header/body gap','bottom edge owns 12px operational header/body gap').replace('Shell notice to floated demo controls; preserves a visible label clearance','Shell notice to normal-flow disclosure; controls remain reachable on every viewport');
standard=standard.replace('Queue filter content after `Toolbar` uses `surface.bodyInsetAfterHeader` so the toolbar owns its top edge and the filter owner supplies only horizontal/bottom inset.', 'Queue filters use `Toolbar.filters` with a flush `FieldGroup`; Toolbar owns the inset and boundary, with no second filter inset.');
standard=standard.replace('21 component + 6 composition contracts trong catalog','mọi public component và composition contracts được discovery trong catalog');
const start=standard.indexOf('**SPC-014'), end=standard.indexOf('\n\n',start);
if(start<0||end<0)throw Error('Missing SPC014');
standard=standard.slice(0,start)+'**SPC-014 — Header–body gap đo theo profile của Panel.** Operational Panel giữ 12px từ đáy nội dung header đến mép child đầu tiên; comfortable reading Panel giữ16px. Header là owner duy nhất; body top0, child flush, inset ngang/bottom theo profile. Khoảng nội bộ của child (DetailLine row, Alert) được đo riêng; không cộng vào header boundary. Không local override hoặc double inset.'+standard.slice(end);
standard=standard.replaceAll('header→first-body gap16 theo SPC-014/068','header→first-body gap12 operational/16 comfortable theo SPC-014/068').replace('header giữ gap đến nội dung đầu 16px theo SPC-014','header giữ gap đến nội dung đầu 12px operational/16px comfortable theo SPC-014');
standard=standard.replace('Pane gutter 16; message bubble inset 12;', 'Pane/composer/list inset12; context12/16; message bubble inset12;').replace('composer inset 16 và action gap 8. List item inset 16; context inset 16/24 theo diện tích.', 'composer action gap8. Khi hẹp, các inset nhỏ vẫn giữ vùng nhập và action targets; bubble/message rhythm4/8/12 không giảm.');
const section=`\n### 4.1. Mật độ theo vai trò — quyết định đã duyệt 09/10/2026\n\nNhịp vận hành mặc định: page block16, section16, surface12 mobile/16 từ768, header-body12, toolbar/pager12, table cell8 dọc/12 ngang, detail row8. Giữ gutter16/24, base8 và scale4/8/12/16/24/32/48; không global shrink theme/font/target. Trường có helper/error dài và form nghiệp vụ phức tạp giữ fieldGap16 mặc định; compact12 là named variant có consumer đơn giản. Các quan hệ4/8 và message bubble/group vẫn giữ nhịp đọc.\n\n| Role bổ sung | Giá trị | Owner/consumer thật |\n|---|---:|---|\n| \`form.compactFieldGap\` | 12 | FormFields density compact; editor danh mục hai trường |\n| \`detail.dividedListGap\` | 0 | SurfaceContent rhythm dividedRows; danh sách capabilities AI gồm DetailLine có divider |\n| \`surface.comfortableInset\` | 16/24 | Panel density comfortable; nội dung kiến thức dài |\n| \`surface.comfortableHeaderInset\` | px/pt16/24, pb16 | Reading Panel header; một owner cho boundary |\n| \`surface.comfortableBodyInsetAfterHeader\` | px/pb16/24, top0 | Reading Panel body; không top inset thứ hai |\n| \`page.majorSectionGap\` | 24 | PageSections rhythm major; nguồn kiến thức và bản xem trước độc lập |\n| \`dialog.compactInset\` | 16 | EditDialog compact mặc định; editor thường |\n\nDialog density comfortable dùng \`dialog.inset\`16/24; ConfirmDialog và DraftConflict chọn comfortable rõ ràng. Dialog actions inset12/gap8; viewport margin16/32 giữ. Stats value gap8/note gap4; notice after12; fallback block16; navigation brand block16/account inset12; auth24/32 và Dashboard hero24/32 giữ. Các geometry roles (header56/64, query section240, chart/pane widths) không giảm máy móc.\n\nDemo warning luôn hiện. Công cụ demo thu/mở tại mọi viewport, mặc định thu; trạng thái role/fault/dataset có summary, selections và status còn nguyên khi thu/mở. Disclosure có aria-controls/expanded và thao tác bàn phím. Không ẩn error/helper, đổi permission/state, fixed row height hoặc font để đạt mật độ. Giữ target44 theo contract dự án; đo hit area thực tế riêng, không suy ra từ size=small.\n\nMọi giá trị và variant mới phải đi qua bridge/type/finite checker/catalog, có negative/positive/rendered regression và source fingerprints mới. Kết quả trước v1.29 là historical source scope; không đổi threshold để gọi run cũ đạt trên profile mới. Đo table, divided rows, ordinary/reading Panels, simple/complex forms, confirmation/conflict dialogs, demo disclosure và responsive/zoom trước đóng.\n\n`;
standard=standard.replace('**SPC-006 —',section+'**SPC-006 —');
fs.writeFileSync(standardFile,standard);
let instructions=fs.readFileSync(path.join(root,'AGENTS.md'),'utf8').replace('chuẩn v1.28','chuẩn v1.29');fs.writeFileSync(path.join(root,'AGENTS.md'),instructions);
let plan=fs.readFileSync(planFile,'utf8');
plan+=`\n\n### 16.20. Thu gọn mật độ theo vai trò — 09/10/2026\n\nNgười dùng đã duyệt triển khai đến hoàn tất kỹ thuật local. Quy định duy nhất là standard v1.29 §4/§4.1; không đổi tokens/base8, dependency, API nghiệp vụ hoặc full-product tracker. Baseline loaded trước source edit: [before.json](../evidence/frontend-spacing-density-20261009/before.json), 216 observations trên54 route/small-large/hai browser; source snapshots và dirty Git được giữ. Design contract/impact: [CONTRACT](../evidence/frontend-spacing-density-20261009/CONTRACT.md).\n\n| Thứ tự | Ưu tiên | Công việc | Trạng thái hiện hành |\n|---|---|---|---|\n| 1 | P0 | Baseline, nguồn quy định v1.29, doc parity/Shared count | SPECIFIED_BASELINE_CAPTURED |\n| 2 | P1 | Table/detail divided rows + permanent regression | IN_PROGRESS |\n| 3 | P1 | Toolbar/pager và disclosure demo giữ state | PENDING_DEPENDENCY_2 |\n| 4 | P1 | Page/header/surface/reading + form/dialog finite variants | PENDING_DEPENDENCY_3 |\n| 5 | P2 | Inbox/stats/report/navigation/footer/empty và all-consumer closure | PENDING_DEPENDENCY_4 |\n| 6 | P0 final | Strict source/unit/verify/full E2E/build/built-demo/native, canonical freshness, handoff | PENDING_DEPENDENCY_5 |\n\nCác kết quả Shared consolidation §16.19 là proof của source trước đợt density. S11–S20 tại §16.6 đang tái xác minh cho source mới; chưa READY/100% cho đợt density cho tới khi mandatory proofs mới đạt cùng source cuối. Human speech, hosted CI và user acceptance ghi đúng quan sát; không tự điền PASS. Mẫu số FE140 giữ nguyên và tái xác minh dependency bằng công cụ canonical.\n`;
plan=plan.replace(/(\| S(?:11|12|14|15|16|17|18|19|20) \|[^\n]*\| )([^|\n]+)( \|)/g,(_,before,status,after)=>before+'DENSITY_REVALIDATION_IN_PROGRESS — §16.20; trạng thái/proof trước: '+status+after);
fs.writeFileSync(planFile,plan);
fs.writeFileSync(path.join(import.meta.dirname,'implementation-start.json'),JSON.stringify({at:new Date().toISOString(),baseline:'before.json',policy:'docs/FRONTEND_SPACING_STANDARD.md v1.29',meaning:'Policy/specification started after immutable loaded baseline; runtime edits follow red regression.'},null,2)+'\n');
console.log('P0 policy/specification published; runtime/evidence completion remains open.');
