export const labels: Record<string, string> = {
    active: 'Đang hoạt động', draft: 'Bản nháp', archived: 'Đã lưu trữ', paused: 'Tạm dừng', degraded: 'Cần kiểm tra', unconfigured: 'Chưa cấu hình',
    open: 'Đang xử lý', resolved: 'Đã giải quyết', bot: 'AI phụ trách', human: 'Nhân viên phụ trách',
    queued: 'Đang chờ', running: 'Đang chạy', accepted: 'Đã tiếp nhận', succeeded: 'Hoàn thành', failed: 'Thất bại', unknown: 'Chưa rõ kết quả',
    sent: 'Đã gửi', delivered: 'Đã giao', read: 'Đã đọc', sending: 'Đang gửi', inbound: 'Khách hàng', outbound: 'Trả lời', internal: 'Nội bộ',
    confirmed: 'Đã xác nhận', completed: 'Hoàn tất', cancelled: 'Đã hủy', unfulfilled: 'Chưa chuẩn bị', reserved: 'Đã giữ hàng',
    picking: 'Đang lấy hàng', packed: 'Đã đóng gói', dispatched: 'Đã bàn giao', in_transit: 'Đang vận chuyển', part_delivered: 'Giao một phần',
    part_returned: 'Hoàn một phần', returned: 'Đã hoàn', returning: 'Đang hoàn về', unpaid: 'Chưa thu', part_paid: 'Thu một phần',
    verified: 'Đã xác minh', cod_collected: 'Đơn vị giao đã thu', settled: 'Đã đối soát', part_refunded: 'Hoàn tiền một phần', refunded: 'Đã ghi nhận hoàn tiền',
    receipt: 'Phiếu thu', disbursement: 'Phiếu chi', posted: 'Đã ghi sổ', reversed: 'Đã đảo', provisional: 'Tạm tính', incomplete: 'Chưa đủ dữ liệu', complete: 'Đủ dữ liệu',
    published: 'Đã xuất bản', ready_for_review: 'Chờ duyệt', processing: 'Đang xử lý', rejected: 'Đã từ chối', retired: 'Ngừng sử dụng',
    connected: 'Đã kết nối', disabled: 'Đã tắt', expired: 'Hết hiệu lực', validating: 'Đang kiểm tra',
    claimed: 'Đã nhận việc', working: 'Đang làm', blocked: 'Bị chặn', pending: 'Đang chờ', pending_approval: 'Chờ phê duyệt', approved: 'Đã duyệt',
    handed_over: 'Đã bàn giao', part_received: 'Nhận một phần', received: 'Đã nhận đủ', awaiting_confirmation: 'Chờ xác nhận', partial: 'Hoàn thành một phần',
    denied: 'Không được phép', revoked: 'Đã thu hồi', accepted_by_provider: 'Nhà cung cấp đã tiếp nhận', in_app: 'Trong ứng dụng', web_push: 'Web Push', telegram: 'Telegram',
    prepare_order: 'Chuẩn bị đơn', purchase_review: 'Duyệt nhập hàng', payment_mismatch: 'Tiền chưa khớp', customer_handoff: 'Khách cần hỗ trợ', late_shipment: 'Đơn giao chậm', recovery: 'Kiểm tra phục hồi',
    draft_for_approval: 'Lập đơn chờ duyệt', notify_only: 'Chỉ cảnh báo', auto_send: 'Tự gửi có hạn mức',
    sales_receipt: 'Thu bán hàng', inventory_purchase: 'Mua hàng nhập kho', shipping: 'Giao hàng', platform_fee: 'Phí nền tảng', payment_fee: 'Phí thanh toán', ai_expense: 'Chi phí AI', operating_expense: 'Chi phí vận hành', capital: 'Vốn góp', loan_principal: 'Gốc khoản vay', transfer: 'Chuyển nội bộ', other: 'Khác',
    owner: 'Chủ shop', manager: 'Quản lý', sales: 'Bán hàng', warehouse: 'Kho hàng', accountant: 'Kế toán', bot_admin: 'Quản trị AI', viewer: 'Chỉ xem',
    cod: 'Thu hộ COD', prepay: 'Trả trước', manual: 'Thủ công', approved_adapter: 'Kết nối được duyệt', passed: 'Đạt', error: 'Lỗi',
    sales_admin: 'Admin bán hàng', inventory_agent: 'Kho & mua hàng', finance_agent: 'Kế toán', supervisor: 'Trưởng nhóm',
    locked: 'Đã khóa', closed: 'Đã đóng', warning: 'Cảnh báo', healthy: 'Bình thường', stale: 'Dữ liệu cũ',
};
export function label(value: string) { return labels[value] || value; }
