import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const read = p => JSON.parse(fs.readFileSync(path.join(root,p),'utf8'));
const api = read('botsales-kit/contracts/openapi.json');
const routes = read('botsales-kit/contracts/route-manifest.json');
const tokens = read('botsales-kit/design/tokens.json');
const permissions = read('botsales-kit/contracts/permission-catalog.json');
const check = process.argv.includes('--check');
let count = 0;
function out(file, text) {
 const dest=path.join(root,file);
 if(check) { if(!fs.existsSync(dest)||fs.readFileSync(dest,'utf8')!==text) throw Error('Generated output stale: '+file); }
 else {fs.mkdirSync(path.dirname(dest),{recursive:true});fs.writeFileSync(dest,text);}
 count++;
}
const q=JSON.stringify;
function ts(s={}) {
 if(s.$ref) return s.$ref.split('/').at(-1);
 if(s.const!==undefined) return q(s.const);
 if(s.enum) return s.enum.map(q).join(' | ');
 if(s.anyOf||s.oneOf) return '('+(s.anyOf||s.oneOf).map(ts).join(' | ')+')';
 if(s.allOf) return '('+s.allOf.map(ts).join(' & ')+')';
 if(Array.isArray(s.type))return s.type.map(t=>ts({...s,type:t})).join(' | ');
 if(s.type==='array')return `Array<${ts(s.items)}>`;
 if(s.type==='object'||s.properties){
  const req=new Set(s.required||[]);
  const props=Object.entries(s.properties||{}).map(([k,v])=>`${q(k)}${req.has(k)?'':'?'}: ${ts(v)};`);
  if(s.additionalProperties===true) props.push('[key: string]: unknown;');
  else if(typeof s.additionalProperties==='object')props.push(`[key: string]: ${ts(s.additionalProperties)};`);
  return '{ '+props.join(' ')+' }';
 }
 return ({string:'string',integer:'number',number:'number',boolean:'boolean',null:'null'})[s.type]||'unknown';
}
const schemas=Object.entries(api.components.schemas).map(([n,s])=>`export type ${n} = ${ts(s)};`).join('\n');
const registry={}; const types=[];
for(const [p, methods] of Object.entries(api.paths)) for(const [m,op] of Object.entries(methods)){
 if(!['get','post','put','patch','delete'].includes(m))continue;
 const params=[...(methods.parameters||[]),...(op.parameters||[])].map(x=>x.$ref?api.components.parameters[x.$ref.split('/').at(-1)]:x);
 const request=op.requestBody?.content?.['application/json']?.schema;
 const response=Object.entries(op.responses).find(([status])=>status.startsWith('2'));
 const responseSchema=response?.[1]?.content?.['application/json']?.schema;
 const pathParams=params.filter(p=>p.in==='path');
 const queryParams=params.filter(p=>p.in==='query');
 registry[op.operationId]={method:m.toUpperCase(),path:p,permission:op['x-permission']||null,requestSchema:request?.$ref?.split('/').at(-1)||null,responseSchema:responseSchema?.$ref?.split('/').at(-1)||null,status:Number(response?.[0]||204),headers:params.filter(p=>p.in==='header').map(p=>({name:p.name,required:!!p.required})),bodyType:op.requestBody?.content?.['multipart/form-data']?'multipart':'json'};
 types.push(`${q(op.operationId)}: { request: ${request?ts(request):op.requestBody?.content?.['multipart/form-data']?'FormData':'undefined'}; response: ${responseSchema?ts(responseSchema):'undefined'}; path: { ${pathParams.map(p=>`${q(p.name)}: ${ts(p.schema)}`).join('; ')} }; query: { ${queryParams.map(p=>`${q(p.name)}${p.required?'':'?'}: ${ts(p.schema)}`).join('; ')} } }`);
}
const pre='// GENERATED by scripts/generate.mjs from kit 2.1.1. Do not edit.\n';
out('packages/contracts/src/generated.ts',pre+schemas+'\nexport interface Operations {\n'+types.join(';\n')+';\n}\nexport type OperationId = keyof Operations;\nexport type RequestOf<K extends OperationId> = Operations[K]["request"];\nexport type ResponseOf<K extends OperationId> = Operations[K]["response"];\nexport type DataOf<K extends OperationId> = ResponseOf<K> extends {data: infer D} ? D : undefined;\n');
out('packages/contracts/src/operations.json',JSON.stringify(registry,null,2)+'\n');
out('packages/contracts/src/schemas.json',JSON.stringify({components:{schemas:api.components.schemas}},null,2)+'\n');
out('packages/contracts/src/routes.json',JSON.stringify(routes,null,2)+'\n');
out('packages/contracts/src/permissions.json',JSON.stringify(permissions,null,2)+'\n');
out('packages/contracts/src/index.ts',pre+"export type * from './generated';\nexport { default as operations } from './operations.json';\nexport { default as routeManifest } from './routes.json';\nexport { default as permissionCatalog } from './permissions.json';\nexport { default as schemaCatalog } from './schemas.json';\n");
out('packages/design-tokens/src/tokens.json',JSON.stringify(tokens,null,2)+'\n');
out('packages/design-tokens/src/index.ts',pre+"import tokens from './tokens.json';\nexport { tokens };\nexport const colors = tokens.colors;\n");
const css='/* GENERATED from approved design/tokens.json. */\n:root{color-scheme:dark;\n'+Object.entries(tokens.colors).map(([k,v])=>`--color-${k.replace(/[A-Z]/g,c=>'-'+c.toLowerCase())}:${v};`).join('\n')+'\n}\n';
out('apps/web/src/app/tokens.css',css);
out('apps/web/public/manifest.webmanifest',JSON.stringify({name:'BotSales AI',short_name:'BotSales',lang:'vi',start_url:'/',scope:'/',display:'standalone',background_color:tokens.colors.canvas,theme_color:tokens.colors.canvas,icons:[{src:'/app-icon.svg',sizes:'any',type:'image/svg+xml',purpose:'any'}]},null,2)+'\n');
out('apps/web/public/app-icon.svg',`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 192 192"><rect width="192" height="192" rx="44" fill="${tokens.colors.canvas}"/><rect x="38" y="56" width="116" height="88" rx="24" fill="${tokens.colors.accent}"/><circle cx="72" cy="94" r="9" fill="${tokens.colors.onAccent}"/><circle cx="120" cy="94" r="9" fill="${tokens.colors.onAccent}"/><path d="M72 123h48M96 36v20" stroke="${tokens.colors.onAccent}" stroke-width="9" stroke-linecap="round"/></svg>\n`);
console.log(JSON.stringify({status:'PASS',outputs:count,schemas:Object.keys(api.components.schemas).length,operations:Object.keys(registry).length,routes:routes.routes.length}));
