import fs from 'node:fs';
import path from 'node:path';
import {createHash} from 'node:crypto';
const output='evidence/frontend-ux-completion-20261009';
const log=fs.readFileSync(path.join(output,'C05-browser-final-r2.log'),'utf8');
if(!/172 passed/.test(log)||/\d+ failed/.test(log))throw new Error('No complete passing browser run.');
const domain=JSON.parse(fs.readFileSync('evidence/domain-tests.json','utf8'));if(domain.status!=='PASS'||domain.network.status!=='PASS')throw new Error('Domain failed.');
const files=[];
function walk(folder){for(const entry of fs.readdirSync(folder,{withFileTypes:true})){const file=path.join(folder,entry.name);if(entry.isDirectory())walk(file);else files.push(file);}}
for(const directory of ['apps/web/src','packages/contracts/src'])walk(directory);
files.push('../botsales-kit/contracts/openapi.json','../botsales-kit/contracts/route-manifest.json','../botsales-kit/contracts/events.schema.json','../botsales-kit/contracts/permission-catalog.json');
const fingerprint=file=>({path:file.replaceAll('\\','/'),sha256:createHash('sha256').update(fs.readFileSync(file)).digest('hex')});
const results={scope:'C05_SYNTHETIC_LOCAL_SCOPED_NOT_FINAL_BATCH_ACCEPTANCE',recordedAt:new Date().toISOString(),status:'VERIFIED_SCOPED',checks:[{command:'node node_modules/@playwright/test/cli.js test tests/ui-master-resources.spec.ts tests/fe011.spec.ts tests/fe012.spec.ts tests/fe014.spec.ts tests/fe015.spec.ts tests/ui-inventory-layout.spec.ts tests/ui-orders-layout.spec.ts tests/ui-toolbar-layout.spec.ts tests/ui-component-layout.spec.ts tests/frontend-corrections.spec.ts --reporter=line --timeout=60000',exitCode:0,expected:172,observed:172,log:'C05-browser-final-r2.log'},{command:'node scripts/test-domain.mjs',exitCode:0,expected:102,observed:102,log:'C05-domain-final-r2.log'},{command:'node node_modules/vitest/vitest.mjs run --config apps/web/vitest.config.ts',exitCode:0,expected:196,observed:196,log:'C05-unit-final.log'},...['type-final-r2','lint-final','generate-final','boundaries-final','layout-final','composition-final','kit-final-r2','contracts-final'].map(check=>({check,exitCode:0,log:`C05-${check}.log`}))],sourceFingerprints:files.map(fingerprint),artifactFingerprints:['C05-browser-final-r2.log','C05-domain-final-r2.log','C05-unit-final.log'].map(file=>fingerprint(path.join(output,file))),limits:['Final full-product/61-route gates, native zoom/text resize and FE revalidation remain C11 work.','Only synthetic MSW; no Backend/provider/statutory/production evidence.','Windows Playwright webServer teardown stalled after workers exited. Verified owned child server was closed with PowerShell; CLI then reported 172 passed and exit 0. Automate/fix teardown before C11 full run.','Historical failed/interrupted runs are retained and are not combined to produce this PASS.','Speech, hosted CI and user acceptance are not observed.']};
fs.writeFileSync(path.join(output,'C05-final.json'),JSON.stringify(results,null,2)+'\n');fs.writeFileSync(path.join(output,'C05-domain-final.json'),JSON.stringify(domain,null,2)+'\n');
const plan='docs/FRONTEND_UI_IMPROVEMENT_PLAN.md';let text=fs.readFileSync(plan,'utf8');text=text.replace('| C04 verified | IN_PROGRESS_IMPLEMENTATION | API 2.1.0, R55/R56 và HTTP 102 checks; regression browser/consumer đang thực hiện, chưa đóng nhóm |','| C04 verified | VERIFIED_SCOPED | API 2.1.0; browser 172/172, unit 196/196, domain/MSW 102/102, kit 522/522; [phạm vi](../evidence/frontend-ux-completion-20261009/C05-scoped-result.md); final closure ở C11 |').replace('| C05 verified | NOT_STARTED | Decimal/immutable/source/period, golden 80k/30k và UI |','| C05 verified | IN_PROGRESS_CONTRACT | Baseline 21 nguồn/10 render; [contract](../evidence/frontend-ux-completion-20261009/C06-CONTRACT.md); implementation/golden/regression còn mở |');fs.writeFileSync(plan,text);
console.log(JSON.stringify({status:'C05_VERIFIED_SCOPED',fingerprints:files.length,next:'C06'}));
