from pathlib import Path
root=Path(__file__).resolve().parents[2]
pending={}
def replace(module,old,new,count=1):
 p=root/f'apps/web/src/modules/{module}'
 s=pending.get(p,p.read_text(encoding='utf-8-sig'))
 assert s.count(old)==count,(module,old,s.count(old))
 pending[p]=s.replace(old,new)

def dialog(module,old,new,action):
 replace(module,'description='+old,'confirmLabel='+action+' description='+new)

dialog('workspace/index.tsx','"Người này không được tiếp tục dùng dữ liệu của shop sau khi quyền được thu hồi."','{`Nhân viên ${remove?.userId || ""} trong ${shop.name}: người này không được tiếp tục truy cập dữ liệu cửa hàng sau khi thu hồi. Lịch sử hoạt động được giữ.`}','"Thu hồi quyền"')
dialog('catalog/index.tsx','"Giữ lại lịch sử đơn hàng; không xóa dữ liệu đã phát sinh."','{`Sản phẩm ${product.data?.data.name || ""} (${productId || ""}): ngừng bán mới; lịch sử đơn hàng và dữ liệu đã phát sinh được giữ.`}','"Ngừng bán sản phẩm"')
dialog('catalog/index.tsx','"Không xóa sản phẩm trong danh mục."','{`Danh mục ${remove?.name || ""} (${remove?.id || ""}): ngừng dùng trong lựa chọn mới; không xóa sản phẩm hoặc lịch sử.`}','"Ngừng dùng danh mục"')
dialog('catalog/imports.tsx','"API kiểm lại token, quyền và phiên bản catalog. Nếu dữ liệu đã thay đổi cần chạy kiểm tra tệp lại."','{`Tệp đã kiểm trong công việc ${jobId}: chỉ ghi các dòng hợp lệ; dòng lỗi không được nhập. Nếu danh mục đã thay đổi, phải kiểm tra tệp lại.`}','"Nhập các dòng hợp lệ"')
dialog('orders/index.tsx','"API sẽ kiểm giai đoạn xử lý và giải phóng lượng hàng giữ khi được phép."','{`Đơn ${orderId}: hủy xử lý mới và giải phóng lượng hàng giữ khi đủ điều kiện. Lịch sử và chứng từ đã ghi được giữ; tác động đã tiếp nhận phải được đối chiếu.`}','"Hủy đơn hàng"')
dialog('procurement/index.tsx','"Chỉ gửi đúng nội dung được duyệt. Quyền mua hàng không cho phép tự chuyển tiền."','{`Đơn mua ${p?.id || resourceId} · ${p?.total.amount || ""} ${p?.total.currency || ""}: gửi đúng nội dung đã được duyệt cho nhà cung cấp ${p?.supplierId || ""}. Không chuyển tiền; kết quả chưa rõ phải được kiểm tra trước khi gửi lại.`}','"Gửi đơn mua"')
dialog('procurement/index.tsx','"Chỉ hủy trong giai đoạn và điều kiện được API cho phép."','{`Đơn mua ${p?.id || resourceId}: hủy tác vụ chưa được tiếp nhận khi đủ điều kiện. Không coi việc hủy UI là thu hồi tác động nhà cung cấp đã nhận.`}','"Hủy đơn mua"')
replace('procurement/index.tsx','title="Ghi nhận hàng đã kiểm vào kho" description=','title="Ghi nhận hàng đã kiểm vào kho" confirmLabel="Ghi nhận vào kho" description=')
replace('inbox/index.tsx',"description={action === 'takeover' ? 'Các câu trả lời AI đang chờ phải bị chặn trước khi gửi.' : 'Hệ thống kiểm lại quyền và phiên bản hội thoại.'}","confirmLabel={action === 'takeover' ? 'Tiếp quản' : action === 'release' ? 'Trả về AI' : 'Đánh dấu đã giải quyết'}\n                        description={`${conversation.displayName} (${conversationId}): ${action === 'takeover' ? 'chuyển trách nhiệm trả lời sang nhân viên và chặn câu trả lời AI đang chờ trước khi gửi.' : action === 'release' ? 'trả trách nhiệm trả lời về AI sau khi kiểm quyền và điều kiện gửi hiện tại.' : 'đánh dấu hội thoại đã giải quyết; lịch sử tin nhắn được giữ.'}`}")
dialog('fulfillment/index.tsx','"Bạn đã kiểm đủ SKU, số lượng và đóng gói thực tế?"','{`Công việc ${resourceId}, đơn ${prep?.orderId || ""}: xác nhận đã kiểm đủ SKU, số lượng và đóng gói thực tế. Bước tiếp theo là bàn giao kiện; chưa xác nhận đã giao cho khách.`}','"Xác nhận đã đóng gói"')
dialog('notifications/index.tsx','"Máy chủ phải dừng mọi thông báo đến subscription này."','{`Thiết bị ${selected?.deviceName || ""} (${selected?.id || ""}): dừng thông báo mới đến đăng ký này. Thông báo đã được kênh tiếp nhận không thể thu hồi.`}','"Thu hồi thiết bị"')
dialog('operations/index.tsx','"Lệnh sử dụng đúng version và tăng generation theo mô phỏng. Đây không phải bằng chứng worker đã dừng hoặc provider đã sẵn sàng; tác động bên ngoài đã được nhận không thể thu hồi."','{`${stop ? roleNames[stop.role.kind] : ""} (${stop?.role.id || ""}) trong ${shop.name}: ${stop?.action === "pause" ? "dừng các tác động chưa được tiếp nhận." : "kiểm điều kiện và chính sách trước khi cho phép tác động mới."} Tác động bên ngoài đã được nhận không thể thu hồi.`}','{stop?.action === "pause" ? "Tạm dừng vai trò" : "Kiểm tra để tiếp tục"}')
dialog('knowledge/index.tsx','"Không xuất bản ngay; API kiểm dữ liệu, phiên bản và quyền."','{`Nguồn ${k?.title || ""} (${knowledgeId}): gửi bản nháp hiện tại vào hàng chờ duyệt; chưa xuất bản hoặc sử dụng trong trả lời khách.`}','"Gửi nguồn để duyệt"')
dialog('knowledge/index.tsx','"Loại nội dung này khỏi tra cứu tiếp theo, không sửa lịch sử câu trả lời trước đó."','{`Nguồn ${k?.title || ""} (${knowledgeId}): loại khỏi tra cứu tiếp theo; lịch sử phiên bản và câu trả lời trước đó được giữ.`}','"Ngừng sử dụng nguồn"')
replace('finance/index.tsx','title={selected?.action === \'post\' ? \'Ghi sổ phiếu đã kiểm\' : \'Đảo phiếu đã ghi\'} description=','title={selected?.action === \'post\' ? \'Ghi sổ phiếu đã kiểm\' : \'Đảo phiếu đã ghi\'} confirmLabel={selected?.action === "post" ? "Ghi sổ phiếu" : "Đảo phiếu"} description=')
dialog('finance/index.tsx','"Backend kiểm kỳ, cân bằng, quyền và chứng từ trùng trước khi ghi."','{`Bút toán ${selected?.journal.id || ""}: ${selected?.action === "post" ? "ghi vào sổ sau khi kiểm kỳ, cân bằng và nguồn chứng từ; bản đã ghi không được sửa trực tiếp." : "tạo bút toán đảo, giữ nguyên chứng từ gốc và lịch sử."}`}','{selected?.action === "post" ? "Ghi sổ bút toán" : "Đảo bút toán"}')
dialog('finance/index.tsx','"Backend kiểm lại chứng từ nháp, sai lệch, COD và quyền trước khi khóa; không xóa sai lệch để vượt kiểm tra."','{`Kỳ ${selected?.id || ""}, từ ${selected?.startDate || ""} đến ${selected?.endDate || ""}: khóa ghi sổ mới sau khi kiểm chứng từ nháp, sai lệch và COD. Mở lại cần quyền và phê duyệt riêng.`}','"Khóa kỳ kế toán"')
dialog('bot/index.tsx','"Dừng các tác động chưa gửi. Tin nhắn đã được nhà cung cấp nhận không thể thu hồi bằng nút này."','{`Admin AI ${b?.id || ""} trong ${shop.name}: dừng các tác động chưa gửi. Tin nhắn đã được nhà cung cấp nhận không thể thu hồi bằng nút này.`}','"Tạm dừng Admin AI"')
dialog('bot/index.tsx','"Không đổi bản đang chạy; phải kiểm thử và duyệt lại trước xuất bản."','{`Cấu hình ${b?.id || ""}, phiên bản ${restoreVersion?.revision || ""}: khôi phục vào bản nháp. Bản đang chạy được giữ; phải kiểm thử và duyệt lại trước xuất bản.`}','"Khôi phục vào nháp"')
dialog('bot/index.tsx','"Kiểm thế hệ tác vụ và chính sách trước tác động mới. Không thu hồi được tác động đã được dịch vụ ngoài nhận."','{`${stop ? roleNames[stop.role.kind] : ""} (${stop?.role.id || ""}) trong ${shop.name}: ${stop?.action === "pause" ? "tạm dừng tác động chưa được tiếp nhận." : "kiểm thế hệ tác vụ và chính sách trước tác động mới."} Không thu hồi được tác động đã được dịch vụ ngoài nhận.`}','{stop?.action === "pause" ? "Tạm dừng vai trò" : "Kiểm tra để tiếp tục"}')
dialog('integrations/index.tsx','"Dừng gửi mới và thu hồi kết nối ở backend. Không xóa lịch sử đơn hàng/hội thoại."','{`Page ${selected?.name || ""} (${selected?.externalPageId || ""}): dừng gửi mới qua kết nối. Lịch sử đơn hàng và hội thoại được giữ; tin đã tiếp nhận không thể thu hồi.`}','"Ngắt kết nối Page"')
dialog('integrations/index.tsx','"Backend kiểm các cấu hình đang sử dụng trước khi xóa; không tự chuyển dữ liệu sang provider khác."','{`Kết nối AI ${deleting?.name || ""} (${deleting?.id || ""}), model ${deleting?.modelId || ""}: chỉ xóa khi không còn cấu hình đang sử dụng. Không tự chuyển dữ liệu sang nhà cung cấp khác.`}','"Xóa kết nối AI"')
dialog('dashboard/index.tsx','"Các tác động chưa gửi sẽ dừng. Tin nhắn nhà cung cấp đã nhận không thể thu hồi."','{`Trợ lý bán hàng ${botConfig?.id || ""} trong ${shop.name}: các tác động chưa gửi sẽ dừng. Tin nhắn nhà cung cấp đã nhận không thể thu hồi.`}','"Tạm dừng trợ lý"')

for p,s in pending.items():p.write_text(s,encoding='utf-8')
print('C03 migrated',len(pending),'module files; 23 confirmation sites')
