import {test,expect} from '@playwright/test';
import type {Page} from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
import {startDemoServer} from './session/demo-server.mjs';
let url='',close:(()=>Promise<void>)|undefined;
test.beforeAll(async()=>{const server=await startDemoServer({cacheIsolationKey:'finance-management-regression'});url=server.url;close=server.close;});
test.afterAll(async()=>close?.());
test.beforeEach(({page})=>page.setDefaultTimeout(15000));
async function choose(page:Page,name:string,value:string){await page.getByRole('combobox',{name,exact:true}).click();await page.getByRole('option',{name:value,exact:true}).click();await expect(page.getByRole('listbox')).toBeHidden();}
async function fresh(page:Page){await page.goto(url+'/s/shop-demo/finance/opening-balances');await expect(page.getByRole('heading',{name:'Mở sổ kế toán',exact:true})).toBeVisible();await page.evaluate(async()=>{const control=await import('/src/mocks/control.ts');await control.setMockControl('dataset','finance-empty');window.history.pushState({},'','/s/shop-demo/finance/ledger');window.dispatchEvent(new PopStateEvent('popstate'));});await expect(page.getByRole('heading',{name:'Sổ cái',exact:true})).toBeVisible();await page.evaluate(()=>{window.history.pushState({},'','/s/shop-demo/finance/opening-balances');window.dispatchEvent(new PopStateEvent('popstate'));});await expect(page.getByRole('heading',{name:'Mở sổ kế toán',exact:true})).toBeVisible();const state=await page.evaluate(async()=>{const {db}=await import('/src/mocks/database.ts');return {journals:db.journals.filter(x=>x.shopId==='shop-demo').length,entries:db.financeEntries.filter(x=>x.shopId==='shop-demo').length,movements:db.movements.filter(x=>x.shopId==='shop-demo').length,stock:db.stock.filter(x=>x.shopId==='shop-demo'&&(Number(x.onHand)>0||Number(x.reserved)>0)).length};});expect(state).toEqual({journals:0,entries:0,movements:0,stock:0});}
async function write(page:Page,path:string,body:unknown,method='POST',version?:number){return page.evaluate(async({path,body,method,version})=>{const session=(await (await fetch('/api/v2/session')).json()).data;const r=await fetch('/api/v2/shops/shop-demo/'+path,{method,headers:{'Content-Type':'application/json','X-CSRF-Token':session.csrfToken,'Idempotency-Key':crypto.randomUUID(),...(version?{'If-Match':`"${version}"`}:{})},body:JSON.stringify(body)});return {status:r.status,payload:await r.json()};},{path,body,method,version});}
async function openingUI(page:Page){await page.getByRole('button',{name:'Tạo nháp mở sổ',exact:true}).click();const dialog=page.getByRole('dialog',{name:'Nháp mở sổ mới',exact:true});await dialog.getByLabel('Ngày mở sổ',{exact:true}).fill('2026-09-01');await dialog.getByLabel('Lý do mở sổ',{exact:true}).fill('Mở sổ ngân hàng đối chiếu tổng hợp');for(let i=1;i<=2;i++){await dialog.getByRole('button',{name:'Thêm số dư tài khoản',exact:true}).click();await choose(page,`Tài khoản số dư ${i}`,i===1?'112 · Tiền ngân hàng':'411 · Vốn chủ sở hữu');await dialog.getByLabel(`${i===1?'Nợ':'Có'} số dư ${i} (VND)`,{exact:true}).fill('2000000');await dialog.getByLabel(`Diễn giải số dư ${i}`,{exact:true}).fill('Số dư mở sổ đã đối chiếu');}const response=page.waitForResponse(r=>r.request().method()==='POST'&&new URL(r.url()).pathname.endsWith('/opening-balances'));await dialog.getByRole('button',{name:'Lưu nháp mở sổ',exact:true}).click();const r=await response,payload=await r.json();expect(r.status(),JSON.stringify(payload)).toBe(201);const opening=payload.data;await expect(dialog).not.toBeVisible();return opening;}

test('C06 opening validates before HTTP and preserves added/removed list drafts through every close guard',async({page})=>{
    await fresh(page);const calls:string[]=[];page.on('request',r=>{if(r.method()==='POST'&&new URL(r.url()).pathname.endsWith('/opening-balances'))calls.push(r.postData()||'');});
    await page.getByRole('button',{name:'Tạo nháp mở sổ'}).click();const dialog=page.getByRole('dialog',{name:'Nháp mở sổ mới',exact:true});await dialog.getByRole('button',{name:'Lưu nháp mở sổ'}).click();await expect(dialog.getByText('Lý do cần ít nhất 5 ký tự.',{exact:true})).toBeVisible();expect(calls).toEqual([]);
    await dialog.getByRole('button',{name:'Thêm tồn đầu kỳ'}).click();await page.keyboard.press('Escape');const guard=page.getByRole('dialog').last();await expect(guard).toContainText('chưa lưu');await guard.getByRole('button',{name:'Tiếp tục sửa',exact:true}).click();await expect(dialog.getByLabel('Kho tồn đầu 1',{exact:true})).toBeVisible();await dialog.getByRole('button',{name:'Lưu nháp mở sổ'}).click();await expect(dialog.getByText('Chọn kho.',{exact:true})).toBeVisible();expect(calls).toEqual([]);
});
test('C06 opening UI posts only its reviewed version and reports/ledger drill down to real journal IDs',async({page})=>{
    await fresh(page);const opening=await openingUI(page);await page.getByRole('button',{name:`Ghi mở sổ ${opening.id}`,exact:true}).click();const confirm=page.getByRole('dialog',{name:'Ghi mở sổ',exact:true});const post=page.waitForRequest(r=>r.method()==='POST'&&new URL(r.url()).pathname.endsWith('/opening-balances/'+opening.id+'/post'));await confirm.getByRole('button',{name:'Ghi mở sổ',exact:true}).click();expect((await post).postDataJSON()).toEqual({expectedVersion:opening.version});await expect(confirm).not.toBeVisible();
    await page.getByRole('link',{name:'Bút toán mở sổ',exact:true}).click();const journal=page.getByRole('dialog',{name:/^Bút toán journal-/});await expect(journal).toBeVisible();await expect(journal).toContainText('2.000.000');await expect(journal.getByRole('button',{name:'Đảo bút toán',exact:true})).toHaveCount(0);
    await journal.getByLabel('Đóng').first().click();await page.getByRole('link',{name:'Cân đối quản trị',exact:true}).click();await expect(page.getByRole('table',{name:'Tài khoản của báo cáo cân đối quản trị'})).toBeVisible();await expect(page.locator('main')).toContainText('Đủ dữ liệu');await expect(page.locator('main')).toContainText('Tiền ngân hàng');
    await page.getByRole('link',{name:'112 · Tiền ngân hàng',exact:true}).click();await expect(page).toHaveURL(/finance\/ledger\?accountId=bank/);await page.getByLabel('Từ ngày',{exact:true}).fill('2026-09-01');await page.getByLabel('Đến trước ngày',{exact:true}).fill('2026-10-01');await expect(page.getByRole('table',{name:'Sổ cái theo chứng từ'})).toContainText('Số dư mở sổ đã đối chiếu');
});
test('C06 opening conflict retains whole lists and reconciles two changing server versions without forced retry',async({page})=>{
    await fresh(page);const o=await openingUI(page);await page.getByRole('button',{name:`Sửa mở sổ ${o.id}`,exact:true}).click();const dialog=page.getByRole('dialog',{name:`Sửa mở sổ ${o.id}`,exact:true});await dialog.getByLabel('Lý do mở sổ',{exact:true}).fill('Nháp lý do của người quản trị');
    const {id:_id,shopId:_shopId,version:_version,createdAt:_createdAt,updatedAt:_updatedAt,status:_status,journalId:_journalId,...body}=o;
    expect((await write(page,'finance/opening-balances/'+o.id,{...body,reason:'Lý do trên server lần 1'},'PUT',1)).status).toBe(200);await dialog.getByRole('button',{name:'Lưu nháp mở sổ'}).click();const compare=page.getByRole('dialog',{name:'Đối chiếu thay đổi',exact:true});await expect(compare).toBeVisible();await choose(page,'Chọn dữ liệu: Lý do','Giữ bản nháp');await compare.getByRole('button',{name:'Áp dụng vào bản nháp'}).click();
    expect((await write(page,'finance/opening-balances/'+o.id,{...body,reason:'Lý do trên server lần 1',effectiveDate:'2026-09-02'},'PUT',2)).status).toBe(200);await dialog.getByRole('button',{name:'Lưu nháp mở sổ'}).click();await expect(compare).toBeVisible();await expect(compare).toContainText('Toàn bộ số dư tài khoản');await compare.getByRole('button',{name:'Áp dụng vào bản nháp'}).click();await expect(dialog.getByLabel('Ngày mở sổ')).toHaveValue('2026-09-02');await expect(dialog.getByLabel('Lý do mở sổ')).toHaveValue('Nháp lý do của người quản trị');await dialog.getByRole('button',{name:'Lưu nháp mở sổ'}).click();await expect(dialog).not.toBeVisible();
});
test('C06 finance entry validation and refetch conflict keep the saved baseline and draft',async({page})=>{
    await page.goto(url+'/s/shop-demo/finance/entries');await page.getByRole('button',{name:'Tạo phiếu',exact:true}).click();const dialog=page.getByRole('dialog',{name:'Phiếu thu chi mới',exact:true});const calls:string[]=[];page.on('request',r=>{if(r.method()==='POST'&&new URL(r.url()).pathname.endsWith('/finance/entries'))calls.push(r.postData()||'');});await dialog.getByRole('button',{name:'Lưu nháp'}).click();await expect(dialog.getByLabel('Số tiền (VND)')).toBeFocused();expect(calls).toEqual([]);await dialog.getByLabel('Số tiền (VND)').fill('10.0001');await dialog.getByLabel('Thời điểm ISO 8601').fill('2026-09-29T14:00:00Z');await dialog.getByLabel('Diễn giải',{exact:true}).fill('Phiếu kiểm chứng phiên bản thực');const response=page.waitForResponse(r=>r.request().method()==='POST'&&new URL(r.url()).pathname.endsWith('/finance/entries'));await dialog.getByRole('button',{name:'Lưu nháp'}).click();const entry=(await(await response).json()).data;await expect(dialog).not.toBeVisible();
    await page.getByRole('row').filter({hasText:entry.id}).getByRole('button',{name:'Chi tiết',exact:true}).click();await page.getByRole('dialog').getByRole('button',{name:'Sửa nháp',exact:true}).click();const edit=page.getByRole('dialog',{name:'Sửa phiếu nháp',exact:true});await edit.getByLabel('Diễn giải',{exact:true}).fill('Bản nháp vẫn được giữ');expect((await write(page,'finance/entries/'+entry.id,{description:'Server sửa đồng thời'},'PATCH',1)).status).toBe(200);await edit.getByRole('button',{name:'Lưu nháp'}).click();const compare=page.getByRole('dialog',{name:'Đối chiếu thay đổi',exact:true});await expect(compare).toContainText('Bản nháp vẫn được giữ');await choose(page,'Chọn dữ liệu: Diễn giải','Giữ bản nháp');await compare.getByRole('button',{name:'Áp dụng vào bản nháp'}).click();await edit.getByRole('button',{name:'Lưu nháp'}).click();await expect(edit).not.toBeVisible();
});
test('C06 all new financial routes and dialog use keyboard/axe and reflow at required widths',async({page,browserName})=>{
    test.setTimeout(180000);
    const routes=[['opening-balances','Mở sổ kế toán','Hồ sơ mở sổ'],['ledger','Sổ cái','Sổ cái theo chứng từ'],['trial-balance','Cân đối phát sinh','Cân đối phát sinh các tài khoản'],['balance-sheet','Cân đối quản trị','Tài khoản của báo cáo cân đối quản trị']];
    for(const width of [320,390,768,1280,1440]){await page.setViewportSize({width,height:900});for(const [route,title,table] of routes){await page.goto(url+'/s/shop-demo/finance/'+route);await expect(page.getByRole('heading',{name:title,exact:true})).toBeVisible({timeout:15000});await expect(page.getByRole('table',{name:table,exact:true})).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth-document.documentElement.clientWidth),`${route}@${width}`).toBeLessThanOrEqual(1);expect((await new AxeBuilder({page}).include('main').analyze()).violations).toEqual([]);}
        await page.goto(url+'/s/shop-demo/finance/opening-balances');await page.getByRole('button',{name:'Tạo nháp mở sổ',exact:true}).focus();await page.keyboard.press('Enter');const dialog=page.getByRole('dialog',{name:'Nháp mở sổ mới',exact:true});await expect(dialog.locator('..')).toHaveCSS('opacity','1');expect((await new AxeBuilder({page}).include('[role="dialog"]').analyze()).violations).toEqual([]);await page.screenshot({path:`evidence/frontend-ux-completion-20261009/C06-opening-${browserName}-${width}.png`});await page.keyboard.press('Escape');await expect(dialog).not.toBeVisible();}
});
