import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import {spawnSync} from 'node:child_process';
const output=import.meta.dirname, frontend=path.resolve(output,'../..'), repository=path.dirname(frontend);
const read=file=>JSON.parse(fs.readFileSync(file,'utf8'));
const hash=file=>crypto.createHash('sha256').update(fs.readFileSync(file)).digest('hex');
const baseline=read(path.join(output,'baseline.json'));
const allowed=['bot/index.tsx','catalog/index.tsx','catalog/imports.tsx','customers/index.tsx','dashboard/index.tsx','finance/index.tsx','operations/index.tsx','orders/index.tsx','procurement/index.tsx','reports/index.tsx'].map(file=>'apps/web/src/modules/'+file).concat(['apps/web/src/shared/ui/components.tsx','apps/web/src/shared/ui/theme.ts','apps/web/src/shared/ui/README.md']);
const changedInputs=Object.entries(baseline.source).filter(([file,sha])=>!fs.existsSync(path.join(frontend,file))||hash(path.join(frontend,file))!==sha).map(([file])=>file);
const unexpectedChanges=changedInputs.filter(file=>!allowed.includes(file));
const before=read(path.join(output,'runs/components-1791457648969-87668/regression-record.json'));
const changedTests=Object.entries(before.sourceFingerprints).filter(([file,sha])=>/^BotSalesAI_Frontend\/(tests|apps\/web\/tests)\//.test(file)&&hash(path.join(repository,file))!==sha).map(([file])=>file.slice('BotSalesAI_Frontend/'.length));
const allowedTests=['apps/web/tests/shared-ui-render-contract.test.tsx','tests/ui-shared-api-contract.test.mjs','tests/ui-component-layout.spec.ts'];
unexpectedChanges.push(...changedTests.filter(file=>!allowedTests.includes(file)));
const originalPaths=baseline.status.trimEnd().split('\n').map(line=>{const value=line.slice(3).split(' -> ').at(-1);return value.startsWith('"')?JSON.parse(value):value;});
const originalPathsMissing=originalPaths.filter(file=>!fs.existsSync(path.join(repository,file)));
const protectedPaths=['botsales-kit/execution/plan.json','botsales-kit/execution/progress.json','botsales-kit/execution/tasks'];
const git=args=>{const result=spawnSync('git',args,{cwd:repository,encoding:'utf8',windowsHide:true});return {args,exitCode:result.status??1,output:(result.stdout||'')+(result.stderr||'')};};
const gitDiffCheck=git(['diff','--check']),fullProductGitCheck=git(['diff','--quiet','HEAD','--',...protectedPaths]);
const beforeProtectedDirty=originalPaths.filter(file=>protectedPaths.some(prefix=>file===prefix||file.startsWith(prefix+'/')));
const record={checkedAt:new Date().toISOString(),baselineHead:baseline.HEAD,scope:'A01–A07 changes against the preserved working tree; unrelated pre-existing work is not replaced or claimed.',changedInputs,allowed,changedTests,allowedTests,newTests:['tests/ui-component-layout.spec.ts','tests/design/component-layout-fixture.tsx'],unexpectedChanges,originalTrackedChanges:baseline.status.split('\n').filter(line=>line&&!line.startsWith('??')).length,originalPaths:originalPaths.length,originalPathsMissing,beforeProtectedDirty,gitDiffCheck,fullProductGitCheck,limits:'No commit, push, staging, reset, clean or deletion. Runtime hashes use before-edit baseline; test hashes use the first failing pre-edit run, which already contains the new component suite. Final additions are enumerated explicitly.'};
fs.writeFileSync(path.join(output,'diff-review-current.json'),JSON.stringify(record,null,2)+'\n');
console.log(JSON.stringify(record));
if(unexpectedChanges.length||originalPathsMissing.length||beforeProtectedDirty.length||gitDiffCheck.exitCode||fullProductGitCheck.exitCode) process.exitCode=1;
