import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import { spawnSync,execFileSync } from 'node:child_process';
const frontend=path.resolve(import.meta.dirname,'../..'),repository=path.dirname(frontend);
const read=file=>JSON.parse(fs.readFileSync(file,'utf8'));
const hash=file=>crypto.createHash('sha256').update(fs.readFileSync(file)).digest('hex');
const baseline=read(path.join(import.meta.dirname,'baseline.json'));
const originalPaths=baseline.trackedChanges.split('\n').filter(Boolean).map(line=>line.slice(3));
const missing=originalPaths.filter(file=>!fs.existsSync(path.join(repository,file)));
const sourceChanges=baseline.files.filter(file=>hash(path.join(frontend,file.path))!==file.sha256).map(file=>({path:file.path,before:file.sha256,after:hash(path.join(frontend,file.path))}));
const result=spawnSync('git',['diff','--check','--','BotSalesAI_Frontend/apps/web/src','BotSalesAI_Frontend/apps/web/tests',...['fe009.spec.ts','fe010.spec.ts','fe012.spec.ts','fe012-source-map.test.mjs','fe013.spec.ts','fe015.spec.ts','fe016.spec.ts'].map(file=>'BotSalesAI_Frontend/tests/'+file)],{cwd:repository,encoding:'utf8',windowsHide:true});
const file=path.join(import.meta.dirname,'diff-check-current.log');fs.writeFileSync(file,(result.stdout||'')+(result.stderr||''));
const canonical=read(path.join(import.meta.dirname,read(path.join(import.meta.dirname,'canonical-revalidation-latest.json')).record));
const kit=path.join(repository,'botsales-kit');
const fullProductDrift=Object.keys(canonical.protectedHashes).filter(file=>hash(path.join(kit,file))!==canonical.protectedHashes[file]);
const protectedPaths=Object.keys(canonical.protectedHashes).map(file=>'botsales-kit/'+file);
const originallyDirtyProtected=protectedPaths.filter(file=>originalPaths.includes(file));
const protectedDiff=spawnSync('git',['diff','HEAD','--exit-code','--',...protectedPaths],{cwd:repository,encoding:'utf8',windowsHide:true});
const protectedLog=path.join(import.meta.dirname,'full-product-diff-current.log');fs.writeFileSync(protectedLog,(protectedDiff.stdout||'')+(protectedDiff.stderr||''));
const record={reviewedAt:new Date().toISOString(),HEAD:execFileSync('git',['rev-parse','HEAD'],{cwd:repository,encoding:'utf8'}).trim(),originalTrackedChanges:originalPaths.length,originalPathsMissing:missing,originalInputs:baseline.files.length,unchangedOriginalInputs:baseline.files.length-sourceChanges.length,sourceChanges,fullProductDrift,fullProductGitCheck:{baselineClean:!originallyDirtyProtected.length,originallyDirtyProtected,exitCode:protectedDiff.status,logSha256:hash(protectedLog)},gitDiffCheck:{exitCode:result.status,logSha256:hash(file)},decisions:['Shared API lifecycle/baseline/dirty guard/comparison reviewed against actual source and owner tests.','16 module/24 file pattern review: dispositions in ANALOGOUS_PATTERNS.md.','No dependency/canonical schema/token change; no reset/clean/bulk-stage/commit.','Original dirty work is retained; preserved snapshots and browser artifact restoration records remain available.','LF/CRLF conversion notices are Git warnings; diff --check has no whitespace errors when exit is 0.']};
fs.writeFileSync(path.join(import.meta.dirname,'diff-review-current.json'),JSON.stringify(record,null,2)+'\n');
if(result.status || missing.length || fullProductDrift.length || originallyDirtyProtected.length || protectedDiff.status)throw new Error('Diff/protected review failed');
console.log(JSON.stringify({originalTrackedChanges:originalPaths.length,originalInputs:baseline.files.length,changedOriginalInputs:sourceChanges.length,missing,fullProductDrift,diffCheck:result.status}));
