"""Generate fixed dark-theme outputs from design/tokens.json. No dependencies.
Run from any cwd: python scripts/generate-theme.py [--check]
--check validates drift without writing. This is not a product accessibility audit.
"""
from pathlib import Path
import argparse,json,re
R=Path(__file__).resolve().parents[1]
def kebab(s):return re.sub(r'([a-z0-9])([A-Z])',r'\1-\2',s).lower()
def outputs():
 release=json.loads((R/'release.json').read_text(encoding='utf-8'));decision=json.loads((R/'design/decision.json').read_text(encoding='utf-8'))
 raw=(R/'design/tokens.json').read_text(encoding='utf-8');t=json.loads(raw)
 if t['theme']!='dark-only':raise ValueError('Only the approved dark-only theme is supported')
 lines=['/* Generated by scripts/generate-theme.py from design/tokens.json. Do not edit. */',':root {','  color-scheme: dark;']
 for k,v in t['colors'].items():lines.append(f'  --color-{kebab(k)}: {v};')
 lines.append(f"  --font-family: {t['fontFamily']};")
 for group,prefix,unit in [('fontSizes','font-size','px'),('space','space','px'),('radius','radius','px'),('layout','layout','px'),('motion','motion','ms'),('zIndex','z','')]:
  for k,v in t[group].items():lines.append(f'  --{prefix}-{kebab(k)}: {v}{unit};')
 lines += ['}','html, body, #root {','  min-height: 100%;','  background-color: var(--color-canvas);','  color: var(--color-text-primary);','}','body { margin: 0; }','@media (prefers-reduced-motion: reduce) {','  :root { --motion-fast-ms: 0ms; --motion-standard-ms: 0ms; }','}']
 css='\n'.join(lines)+'\n'
 palette=[f"# Graphite Gold — bảng màu đã duyệt | Gói {release['version']} | Token {t['version']}",'',"Quyết định: `design/decision.json` (ADR-VIS-021, APPROVED). Giá trị giữ nguyên bản 2.1; không chọn lại palette.",'',"Sinh từ `design/tokens.json`; một theme dark-only. Giá trị là thiết kế riêng của BotSales, không phải token chính thức của Binance/Bybit/Coinbase.",'','| Token | HEX |','|---|---|']
 palette += [f'| `{k}` | `{v}` |' for k,v in t['colors'].items()]
 result={'design/tokens.css':css,'prototype/src/tokens.css':css,'prototype/src/tokens.json':raw,'design/PALETTE.md':'\n'.join(palette)+'\n'}
 doc=(R/'docs/03_DESIGN_SYSTEM.md').read_text(encoding='utf-8')
 roles=[('canvas','Nền ứng dụng'),('surface','Card, bảng và dialog'),('raised','Bề mặt nổi'),('textPrimary','Chữ chính'),('textSecondary','Chữ phụ'),('onAccent','Chữ tối trên CTA vàng'),('accent','CTA, mục chọn, liên kết'),('accentHover','CTA khi rê chuột'),('accentPressed','CTA khi nhấn'),('borderDecorative','Viền trang trí'),('borderControl','Biên input có ý nghĩa'),('success','Thành công, có nhãn'),('warning','Cảnh báo, có nhãn'),('danger','Lỗi, có nhãn'),('info','Thông tin, không là CTA')]
 table='<!-- BEGIN GENERATED CORE PALETTE -->\n| Token nguồn | HEX đã duyệt | Cách dùng |\n|---|---|---|\n'+'\n'.join(f'| `colors.{k}` | `{t["colors"][k]}` | {label} |' for k,label in roles)+'\n<!-- END GENERATED CORE PALETTE -->'
 doc,count=re.subn(r'<!-- BEGIN GENERATED CORE PALETTE -->.*?<!-- END GENERATED CORE PALETTE -->',lambda _:table,doc,flags=re.S)
 if count!=1:raise ValueError('docs/03 must have one generated palette region')
 result['docs/03_DESIGN_SYSTEM.md']=doc
 return result
if __name__=='__main__':
 a=argparse.ArgumentParser();a.add_argument('--check',action='store_true');args=a.parse_args();drift=[]
 for name,text in outputs().items():
  p=R/name
  if args.check:
   if not p.exists() or p.read_text(encoding='utf-8')!=text:drift.append(name)
  else:p.write_text(text,encoding='utf-8')
 if drift:raise SystemExit('THEME_DRIFT: '+', '.join(drift))
 print('Theme outputs consistent' if args.check else 'Generated canonical dark-only theme outputs')
