import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import {pathToFileURL} from 'node:url';import {createRequire} from 'node:module';
const root=path.resolve('BotSalesAI_Frontend'),require=createRequire(path.join(root,'package.json')),{chromium,firefox,expect}=require('@playwright/test'),ts=require('typescript');const {startDemoServer}=await import(pathToFileURL(path.join(root,'tests/session/demo-server.mjs')));
const folder=path.resolve('.git/codex-delivery/orders-probe-v3');fs.mkdirSync(folder,{recursive:true});const server=await startDemoServer({cacheIsolationKey:'orders-detail-readiness-probe-v3'}),browser=await firefox.launch(),chromiumBrowser=await chromium.launch(),results=[];
try{for(const mode of ['baseline','data','lazy'])for(const fixture of mode==='baseline'?['original']:['original','candidate']){
const source=fs.readFileSync('.git/codex-delivery/orders-'+fixture+'.spec.ts','utf8').replaceAll('\r\n','\n'),tree=ts.createSourceFile('fixture.ts',source,ts.ScriptTarget.Latest,true,ts.ScriptKind.TS),node=tree.statements.find(statement=>ts.isExpressionStatement(statement)&&ts.isCallExpression(statement.expression)&&statement.expression.arguments[0]?.text?.startsWith('Orders draft, versioned quote'));
assert(node);const compiled=ts.transpileModule('const target='+node.expression.arguments[1].getText(tree)+';',{compilerOptions:{target:ts.ScriptTarget.ES2022}}).outputText,target=new Function('expect','demoUrl',compiled+'return target;')(expect,server.url);
const context=await (mode==='lazy'?chromiumBrowser:browser).newContext({viewport:{width:1280,height:900}});context.setDefaultTimeout(30000);await context.tracing.start({screenshots:true,snapshots:true,sources:true});const page=await context.newPage();for(const method of ['waitForResponse','waitForRequest']){const native=page[method].bind(page);page[method]=(...args)=>{const pending=native(...args);void pending.catch(()=>undefined);return pending;};}
const label=mode+'-'+fixture,pending=new Set(),network=[],writes=[],dataDelays=[];let moduleRequests=0,delayedRequests=0;
if(mode==='lazy')await context.route('**/src/modules/orders/index.tsx',route=>{moduleRequests++;if(moduleRequests!==2)return route.continue();delayedRequests++;const task=(async()=>{const response=await route.fetch();await new Promise(resolve=>setTimeout(resolve,6500));await route.fulfill({response});})();pending.add(task);return task.finally(()=>pending.delete(task));});
if(mode==='data'){
await page.exposeFunction('__ordersRecordDelay',row=>{dataDelays.push(row);});
await page.addInitScript(()=>{const nativeFetch=window.fetch.bind(window);let initialDelayed=false;window.fetch=async(input,init)=>{const request=input instanceof Request?input:null,url=new URL(request?request.url:String(input),location.href),method=(init?.method||request?.method||'GET').toUpperCase();const response=await nativeFetch(input,init);if(method==='GET'&&url.pathname==='/api/v2/shops/shop-demo/orders/DH-1001'&&!initialDelayed){initialDelayed=true;await window.__ordersRecordDelay({phase:'start',path:url.pathname,at:Date.now(),delayMs:6500});await new Promise(resolve=>setTimeout(resolve,6500));await window.__ordersRecordDelay({phase:'end',path:url.pathname,at:Date.now(),delayMs:6500});}return response;};});}
page.on('response',response=>network.push({url:response.url(),status:response.status(),at:Date.now()}));page.on('request',request=>{if(['POST','PATCH','DELETE'].includes(request.method())&&new URL(request.url()).pathname.startsWith('/api/v2/'))writes.push({method:request.method(),path:new URL(request.url()).pathname,body:request.postDataJSON()});});
let status='PASS',error;const started=Date.now();try{await target({page});}catch(failure){status='FAIL';error=failure.message;fs.writeFileSync(path.join(folder,label+'.html'),await page.content());await page.screenshot({path:path.join(folder,label+'.png'),fullPage:true});}
await Promise.allSettled([...pending]);if(mode==='data'&&status==='FAIL')await page.waitForFunction(()=>document.querySelector('main')?.textContent?.includes('Phiên bản 1'));
if(mode==='baseline'){for(const width of [390,1280]){await page.setViewportSize({width,height:900});const read=page.waitForResponse(response=>response.request().method()==='GET'&&new URL(response.url()).pathname==='/api/v2/shops/shop-demo/orders/DH-1001');await page.goto(new URL('/s/shop-demo/orders/DH-1001',server.url).toString());assert.equal((await read).status(),200);await page.locator('main#main-content').getByRole('progressbar',{name:'Đang tải dữ liệu',exact:true}).waitFor({state:'hidden'});await expect(page.getByText('Phiên bản 1',{exact:true})).toBeVisible();await page.screenshot({path:path.join(folder,'baseline-loaded-'+width+'.png'),fullPage:true});fs.writeFileSync(path.join(folder,'baseline-loaded-'+width+'.html'),await page.content());}}
const elapsedMs=Date.now()-started;assert(elapsedMs<180000);results.push({mode,fixture,status,error,engine:mode==='lazy'?'chromium':'firefox',wholeOrdersDialogCallback:true,detailViewport:[390,844],returnWidths:[390,1280],sourceDefaultTimeoutMs:30000,sourceExpectTimeoutUnchanged:5000,sourceTestTimeoutUnchanged:180000,elapsedMs,moduleRequests,delayedModuleOrdinal:mode==='lazy'?2:null,delayedRequests:mode==='data'?dataDelays.filter(row=>row.phase==='start').length:delayedRequests,delayMs:mode==='baseline'?0:6500,dataDelays,writes});fs.writeFileSync(path.join(folder,label+'.network.json'),JSON.stringify(network,null,2));await context.tracing.stop({path:path.join(folder,label+'.zip')});await context.close();console.log(JSON.stringify(results.at(-1)));
}}finally{await browser.close();await chromiumBrowser.close();await server.close();fs.writeFileSync(path.join(folder,'results.json'),JSON.stringify(results,null,2));}
assert.equal(results[0].status,'PASS');for(const mode of ['data','lazy']){const rows=results.filter(row=>row.mode===mode);assert.equal(rows[0].status,'FAIL');assert.match(rows[0].error,/Phiên bản 1/);assert.equal(rows[1].status,'PASS');assert(rows.every(row=>row.delayedRequests===1));assert.equal(rows[1].writes.length,1);assert(rows[1].writes.every(row=>row.method==='POST'&&row.path==='/api/v2/shops/shop-demo/orders/DH-1001/quote'));}console.log('Orders controlled probes verified, owner source unchanged.');
