// GENERATED by scripts/generate.mjs from kit 2.1.1. Do not edit.
export type * from './generated';
export { API_BASE_PATH } from './generated';
export { default as operations } from './operations.json';
export { default as routeManifest } from './routes.json';
export { default as permissionCatalog } from './permissions.json';
export { default as schemaCatalog } from './schemas.json';
